import type { QuestionBank } from './types';

export const bank: QuestionBank = {
  topic: 'concurrency',
  questions: [
    // --- junior ---
    {
      level: 'junior',
      question: 'What\'s the difference between concurrency and parallelism?',
      answer:
        'Rob Pike\'s line: **concurrency is about *dealing* with many things at once; parallelism is about *doing* many things at once.** Concurrency is a property of how a program is *structured*; parallelism is a property of how it *runs*.\n\nA single-core machine can run a concurrent program just fine — the scheduler interleaves tasks. Add cores and the same program may run in parallel. Same code, different execution.\n\nFor I/O-bound work (web servers, scrapers), concurrency alone often suffices — your bottleneck is the network, not CPU. For CPU-bound work (image encoding, big numeric loops), parallelism is what moves the needle. The bugs differ too: concurrency bugs are about *interleaving* (races on a single core); parallelism bugs are about *simultaneous execution* (false sharing, memory ordering on multiple cores).',
    },
    {
      level: 'junior',
      question: 'A race condition — what is it, and why is it harder than "two threads writing at the same time"?',
      answer:
        'A race condition is when the **correctness of a program depends on the timing of concurrent operations.** Three flavors:\n\n1. **Read-modify-write race** (lost update). `counter = counter + 1` is three machine instructions; two threads can both read, both increment, both store — net result: one increment instead of two.\n2. **Check-then-act (TOCTOU)**. `if !exists(path); create(path);` — between check and act, someone else created it. The fix isn\'t "check again"; it\'s an atomic primitive like `O_CREAT | O_EXCL` or `INSERT … ON CONFLICT`.\n3. **Publication race**. One thread writes `data` then sets `ready=true`. Another reads `ready` then uses `data`. Without a memory barrier, the reader may see `ready=true` with stale `data` because the CPU reordered the writes.\n\nThe properties that make them hard: **non-determinism** (only certain interleavings fire), **silent corruption** (wrong-but-plausible values propagate), and **observer effect** (adding logging changes timing and "fixes" the bug).',
    },
    {
      level: 'junior',
      question: 'What does it mean for an operation to be "atomic," and why isn\'t `n++` atomic?',
      answer:
        'An operation is **atomic** if other concurrent actors only see it as either "not started yet" or "completely done." There\'s no intermediate state for them to observe.\n\n`n++` is three machine instructions: load `n` into a register, add 1, store back. Two threads running `n++` can interleave: T1 loads (sees 0), T2 loads (sees 0), T1 adds and stores (writes 1), T2 adds and stores (writes 1). Two increments, one result.\n\nThree fixes:\n\n- **Mutex around the operation.** Cheap when uncontended (one CAS in user space), straightforward.\n- **Atomic primitive**: `std::atomic<int>` (C++), `AtomicInteger` (Java), `sync/atomic` (Go). The CPU has dedicated instructions (`LOCK XADD`) that perform load-modify-store as one indivisible op.\n- **Lock-free CAS loop**: `do { old = n.load(); } while (!n.compare_exchange(old, old+1));` Same effect, more flexibility for non-trivial updates.\n\nThe core insight: **atomicity doesn\'t compose.** Two atomic operations sequenced are not atomic. That\'s why combining operations into one primitive (like `putIfAbsent`) matters.',
    },
    {
      level: 'junior',
      question: 'What is a mutex, and what is the "fast path" people talk about?',
      answer:
        'A mutex ("mutual exclusion") is a piece of state — usually a single integer plus a wait queue — that lets only one thread at a time enter a critical section. The two operations are `lock` and `unlock`.\n\nThe **fast path** is what happens when there\'s no contention: a single atomic compare-and-swap on the mutex word. "If it\'s 0 (free), set to 1 (held)." About 10-20 cycles, entirely in user space, no syscall.\n\nThe **slow path** is contention: the CAS fails because someone else holds the lock. The thread enters the kernel via a **futex** syscall and sleeps on the mutex\'s wait queue. When the holder releases, it issues another futex to wake one waiter.\n\nThis is why `pthread_mutex_lock` "feels free" most of the time — it usually is. The kernel only gets involved when threads actually fight for the lock. `std::mutex`, `sync.Mutex`, Java `synchronized`, all use this same pattern.',
    },
    {
      level: 'junior',
      question: 'What does "thread-safe" actually mean?',
      answer:
        'Goetz\'s definition: **a class is thread-safe if it behaves correctly when accessed from multiple threads, with no additional synchronization required by the caller, regardless of how those threads are interleaved by the runtime.**\n\nThree things it\'s *not*:\n\n- Not "uses a lock somewhere." A locked class can still expose internal state via a getter the caller mutates.\n- Not "fast under concurrent access." A correct but slow class is still thread-safe.\n- Not "deadlock-free in combination with everything else." Safety is per-class; deadlock is system-wide.\n\nThe taxonomy (Pugh):\n\n1. **Immutable** — state can\'t change; no sync needed. Cheapest safety.\n2. **Thread-safe** — all ops safe in any order. `ConcurrentHashMap`.\n3. **Conditionally thread-safe** — single ops safe; some sequences need external sync. `Collections.synchronizedList` for iteration.\n4. **Thread-compatible** — not safe; safe with external sync. `ArrayList`.\n5. **Thread-hostile** — can\'t be made safe. Design bug.\n\nThe cheapest paths to thread safety are immutability and not sharing. Locks come third.',
    },
    {
      level: 'junior',
      question: 'When would you pick blocking I/O vs async I/O?',
      answer:
        'The difference isn\'t about speed; it\'s about **who holds the thread while we wait.** Blocking parks the thread until the I/O completes. Async returns a future/promise immediately; the thread is free to do other work.\n\n- **Blocking model**: one OS thread per concurrent operation. ~1MB stack each. Thousands of concurrent ops feasible; tens of thousands painful; hundreds of thousands impossible.\n- **Async model**: one thread handles many concurrent ops via an event loop. Hundreds of thousands of connections on a single thread is routine.\n\nWhen to pick blocking:\n\n- Pure CPU work. No I/O to overlap; async adds overhead.\n- Low concurrency (say, 5 background tasks). Thread cost is negligible.\n- Simpler debugging — stack traces show the whole call chain.\n- You\'re calling sync libraries that don\'t have async APIs.\n\nWhen to pick async:\n\n- High concurrency with I/O. Web servers, scrapers, pipelines.\n- Long tail latency that you don\'t want to consume threads.\n- You need cooperative cancellation that\'s actually safe.\n\nMost mature ecosystems let you mix: async for I/O orchestration, a blocking thread pool (`spawn_blocking`) for the CPU stages.',
    },
    {
      level: 'junior',
      question: 'What is a future (or promise), and what are its three states?',
      answer:
        'A future (or promise — synonyms in most ecosystems) is a handle to a value that isn\'t available yet. The computation runs elsewhere; you get the result by `await`-ing, calling `.then(...)`, or blocking on `get()`.\n\nThree states:\n\n- **Pending**: in flight, no result yet.\n- **Fulfilled**: completed with a value.\n- **Rejected**: failed with an error.\n\nOnce settled (fulfilled or rejected), the state is final. A future never goes back to pending or changes its value. This immutability is what makes futures composable — `Promise.all([a, b, c])` works because each input has a definite eventual answer.\n\nKey variant to know: **eager vs lazy.** JavaScript promises are eager — creating one starts the work. Rust futures are lazy — they do nothing until the runtime polls them. Eager is friendlier ("calling the function does what you\'d expect"); lazy is more controllable (drop the future, work stops).\n\nThe most common bug: forgetting to `await`. The promise sits unawaited; if it rejects, you get an `UnhandledPromiseRejection`; if it resolves, the result is lost.',
    },

    // --- mid ---
    {
      level: 'mid',
      question: 'Walk me through what async/await actually compiles to.',
      answer:
        'Under the hood, async code is a **state machine**. The compiler or runtime breaks your function at every `await` into chunks. Each `await` becomes a "save state, return Pending; resume here when ready" point.\n\nFor a function like:\n\n```\nasync def fetch_and_save():\n    request = await http_send(url)\n    response = await request\n    await save(response)\n```\n\nThe compiler produces (roughly):\n\n```\nclass State:\n    n = 0\n    def poll():\n        match n:\n            0 -> req = http_send(url); n = 1; return Pending(waker for socket)\n            1 -> resp = req.poll(); if pending: return Pending; n = 2; ...\n            2 -> save_fut.poll(); if pending: return Pending; return Done\n```\n\nThe runtime calls `poll` whenever the awaited I/O is ready. The function "resumes" by re-entering at the right state.\n\nThe straight-line `await` syntax is sugar over this. Before async/await, you wrote callbacks or `.then` chains; the state machine was hidden inside the runtime. Now the *syntax* matches the sequential mental model but the *semantics* are still "yield to the runtime at each I/O wait."\n\nOne notable difference between languages: Rust generates the state machine struct sized exactly for the locals across await points (very compact). JS, Python, C# allocate a coroutine object on the heap (slightly larger). Go skips this entirely — goroutines have real stacks, suspension is a stack switch.',
    },
    {
      level: 'mid',
      question: 'Channels vs mutexes — when do you reach for each?',
      answer:
        'Cox-Buday\'s framing from *Concurrency in Go*: **mutexes protect invariants; channels coordinate goroutines.**\n\nReach for a **mutex** when you have a small piece of shared state with multiple readers/writers and you need to keep its invariants consistent. `userCache` shared between request handlers — mutex.\n\nReach for a **channel** when you\'re passing values between concurrent tasks. The classic patterns:\n\n- **Fan-out**: many workers pulling from one shared channel. Load-balancing for free.\n- **Fan-in**: many workers producing into one shared channel. Aggregation point.\n- **Pipeline**: stages chained, each running in its own goroutine.\n- **Cancellation/done broadcast**: `close(done)` instantly signals all listeners.\n\nThe two anti-patterns:\n\n- **Channel as mutex** — a single-element channel "owns" a variable; sending and receiving lock and unlock. More code, slower than a mutex, harder to read.\n- **Mutex orchestrating goroutines** — sleeping on a condition variable that\'s really "wait for this work to be done." Use a channel.\n\nThe Pike slogan is "don\'t communicate by sharing memory; share memory by communicating," but it\'s a guideline. Pure channel-only code can be cumbersome for simple shared state.',
    },
    {
      level: 'mid',
      question: 'What is the actor model and what does it eliminate?',
      answer:
        'An actor is an isolated entity that owns its private state and communicates with other actors *only* by sending asynchronous messages. No shared memory, no locks, no critical sections. Three capabilities: receive messages, send messages, create new actors.\n\nThe defining property: **share-nothing**. Because nothing is shared, most concurrency bugs are impossible by construction:\n\n- **No races** — only one message is processed at a time per actor; the actor is the unit of serialization. Two actors can run truly in parallel because they don\'t touch each other\'s state.\n- **No deadlocks from lock ordering** — no locks at all.\n- **No ABA, no memory-ordering hazards** — no concurrent access to reorder around.\n\nYou trade these for new problems:\n\n- **Mailbox management** — unbounded mailboxes are memory bombs under load. Use bounded mailboxes or `ask`-with-future patterns.\n- **Message ordering** — FIFO between any two actors, but not across senders.\n- **Crash semantics** — "let it crash" relies on **supervision**: a supervisor restarts crashed children from a known good state. The system survives even though components die.\n\nUsed heavily in: Erlang/Elixir (BEAM), Akka (JVM), Orleans (.NET). The sweet spot is stateful long-lived entities — chat sessions, IoT controllers, game NPCs. Pure CPU work doesn\'t need actors; a thread pool is faster.',
    },
    {
      level: 'mid',
      question: 'What\'s structured concurrency, and what does it solve?',
      answer:
        'Structured concurrency is the discipline (and increasingly a language feature) that **a concurrent task can never outlive the scope that started it.** The named primitives: `TaskGroup` (Python/Swift), `coroutineScope` (Kotlin), nursery (Trio), `StructuredTaskScope` (Java JEP 462).\n\nThe problem it solves: unstructured `go work()` / `setTimeout(fn)` / `asyncio.create_task` patterns. Three issues those create:\n\n1. **Leaks.** If a function returns while a child task is still running, the parent doesn\'t know. The child can run forever.\n2. **Errors are swallowed.** If the background task throws after the parent returned, the error has no caller to propagate to.\n3. **Cancellation doesn\'t compose.** Canceling the parent doesn\'t cancel the children.\n\nThe TaskGroup contract:\n\n- The scope doesn\'t exit until every child has finished.\n- If any child raises, the others are cancelled.\n- The error propagates up through the scope.\n- The scope owns the children — external code can\'t spawn into it.\n\nThe pause at scope exit is the key idea: like a `Promise.all` built into the language. You can\'t "forget" a task because the scope refuses to exit while one is running. Combined with cancellation tokens, timeouts become trustworthy: `with timeout(5s)` wraps a structured scope; if it fires, everything inside is cancelled together.',
    },
    {
      level: 'mid',
      question: 'Why is cancellation always cooperative, and what breaks if it isn\'t?',
      answer:
        'Cancellation is cooperative because you can\'t safely yank a thread or task mid-operation. It might be holding locks, midway through a transaction, or mid-write to a file. Forcibly killing it leaves the system in a corrupt state.\n\nThe POSIX `pthread_cancel` *is* asynchronous cancellation, and it\'s notoriously a minefield. Cancel points are only at specific syscalls; cleanup handlers must be registered manually; partial states are common. Most production code disables async cancellation entirely.\n\nThe correct pattern is **cooperative**: the caller signals "stop" (`AbortSignal`, `CancellationToken`, `context.Done()`, `Task.cancel()`); the callee checks the signal at safe points (each `await`, each loop iteration); on detection, the callee cleans up and returns or raises.\n\nWhat breaks without cooperation:\n\n- Held locks stay held forever — system-wide deadlock.\n- Half-committed transactions leave DB rows inconsistent.\n- Partial file writes leave corrupted state on disk.\n- Resources like FDs, network connections leak.\n\nThe right design: every async I/O API takes a cancellation parameter; every internal loop checks it; cleanup is shielded from further cancellation (e.g., Python\'s `asyncio.shield`, Go 1.21\'s `WithoutCancel`).',
    },
    {
      level: 'mid',
      question: 'What\'s backpressure, and what happens to a system without it?',
      answer:
        'Backpressure is the mechanism by which a slow consumer signals "please slow down" to a fast producer. Without it, the queue between them grows without bound — RAM fills, GC thrashes, latency spikes, the process dies.\n\nFour responses to overflow:\n\n1. **Block** — sender waits until consumer drains. Cascade slows; deadlock risk if cyclic.\n2. **Drop** — discard excess items. Acceptable for sampling/telemetry; usually requires a metric to count drops.\n3. **Buffer** — queue up excess. Bounded buffer must fall back to one of the other three when full.\n4. **Reject** — sender gets an error/fail-fast. Best for external APIs.\n\nThe mistake everyone makes once: trying to be nice by using an unbounded queue. Under sustained overload, it delays the crash and makes failure worse (a 10GB queue full of stale work nobody wants).\n\nHow primitives provide it:\n\n- **Unbuffered channels** — sender blocks until receiver receives. Backpressure for free.\n- **Buffered channels** — sender blocks when buffer full. Tunable burst tolerance.\n- **Async iterators / streams** — consumer pulls; producer waits.\n- **`writable.write` returning `false`** — Node streams\' signal to call `once("drain")`.\n\nThe right end-to-end goal: pressure at the slow consumer propagates all the way back to the source, so the entire pipeline self-regulates. Without that, you have a system that\'s one slow consumer away from OOM.',
    },
    {
      level: 'mid',
      question: 'Fan-out, fan-in, pipeline — explain each and when to use them.',
      answer:
        '**Fan-out**: one source, many workers. A producer hands items to a pool of workers; each worker takes the next item, processes it, emits results. The number of workers is the parallelism knob — `numCores` for CPU-bound, hundreds for I/O-bound.\n\n```\nfor i := 0; i < N; i++ {\n    go worker(jobs, results)\n}\nfor _, j := range allJobs { jobs <- j }\nclose(jobs)\n```\n\n**Fan-in**: many sources, one sink. The mirror image. Each worker has its own output; one collector merges them. `Promise.all` is fan-out + fan-in: kicks off all promises, waits for all of them.\n\n**Pipeline**: stages in sequence, each running in its own goroutine/task. Each stage reads from its input, transforms, writes to its output. Stages run concurrently — `stage1` produces while `stage2` consumes. Backpressure flows upstream naturally.\n\n```\nsource → fetch → parse → save\n         (concurrent with each other)\n```\n\nThe combinations dominate real-world ETL:\n\n- Fetch stage: I/O-bound, 50 concurrent (limited by remote service)\n- Parse stage: CPU-bound, 8 concurrent (limited by cores)\n- Save stage: I/O-bound, batched 100 at a time (limited by DB)\n\nThe key discipline: match worker count to each stage\'s bottleneck, propagate cancellation through every stage, and close channels in order on shutdown so downstream stages see "no more values" and finish cleanly.',
    },
    {
      level: 'mid',
      question: 'A coroutine and a thread — what\'s the difference?',
      answer:
        'A coroutine is a function that can **suspend itself and resume later**, preserving its local state across the gap. Unlike a function (one entry, one exit), a coroutine has many entry points — each `yield` or `await`.\n\nA thread is an OS-scheduled execution unit with its own stack, scheduled preemptively by the kernel. ~1MB stack each, several µs to context-switch.\n\nThe key dimensions:\n\n- **Scheduling**: threads = preemptive (kernel decides); coroutines = cooperative (yield explicit).\n- **Cost**: threads = MB of stack each, thousands max practical; coroutines = bytes to KB, millions possible.\n- **Concurrency model**: threads = parallel by default; coroutines = concurrent, parallel only if the runtime supports it.\n\nThe big architectural split: **stackless vs stackful coroutines.**\n\n- **Stackless** (Rust, Python `async def`, JS `async`, C#) = compiler turns the function into a state-machine struct. Tiny per-coroutine. Suspends only at explicit await points.\n- **Stackful** (Go, Java Loom, Erlang, Lua) = full stack per coroutine. Suspends from anywhere. Slightly heavier (still much lighter than OS threads).\n\nIn practice: async/await is stackless coroutines tied to an event loop. Goroutines are stackful coroutines on an M:N scheduler. Both let you have millions of "tasks" without millions of OS threads; the difference is whether your code needs `await` annotations (stackless) or looks synchronous (stackful).',
    },

    // --- senior ---
    {
      level: 'senior',
      question: 'Explain happens-before and why it matters for cross-thread visibility.',
      answer:
        'Happens-before is a partial ordering on the events of a multi-threaded execution. If event A *happens-before* B, B is guaranteed to see A\'s effects. If no happens-before edge connects them, no visibility is guaranteed — even if A finished "before" B started in wall-clock time.\n\nThe happens-before edges every modern language defines:\n\n- Program order within a thread.\n- Unlock happens-before subsequent lock of the same mutex.\n- Atomic store-release happens-before atomic load-acquire of the same variable seeing that value.\n- Thread start happens-before that thread\'s first action.\n- Thread\'s actions happen-before its join.\n- (Java) Volatile write happens-before subsequent read.\n\nWhy it matters: without an explicit edge, the CPU and compiler are allowed to reorder operations across threads. A thread that reads `ready = true` is *not* guaranteed to see the writes the publishing thread did before setting `ready` — unless there\'s a happens-before chain.\n\nThe classic broken pattern: write `data`, then write `ready = true`, expecting a reader to see both. Without `volatile`/atomic-release on `ready` and the matching acquire on the reader, the reader can see `ready = true` with stale `data`. The fix is making `ready` a synchronization primitive that establishes the happens-before edge.\n\nThe rule of thumb: any cross-thread communication must go through a primitive that documents happens-before semantics — mutex, atomic, channel, async barrier, volatile field.',
    },
    {
      level: 'senior',
      question: 'Lock-free vs wait-free — what\'s the actual difference?',
      answer:
        'The hierarchy (Herlihy, 1991) — from weakest to strongest:\n\n1. **Blocking** — one thread can stall the whole structure (takes a lock then gets descheduled).\n2. **Obstruction-free** — a thread makes progress if it runs alone; contention may stall all.\n3. **Lock-free** — at least *one* thread makes progress in any finite number of steps.\n4. **Wait-free** — *every* thread completes its operation in a bounded number of steps.\n\nLock-free means the *system* always makes progress; wait-free means *every individual thread* always makes progress.\n\nMost "lock-free" claims in real systems mean lock-free, not wait-free. The difference: under heavy contention, a lock-free CAS loop can starve an unlucky thread indefinitely while others succeed. A wait-free structure guarantees bounded latency for every caller — what hard real-time systems need.\n\nWait-free is much harder to implement. The single-producer-single-consumer (SPSC) queue is wait-free easily. Multi-producer multi-consumer wait-free queues exist (Kogan-Petrank) but are complex and rarely faster than well-tuned lock-free versions.\n\nThe pragmatic guidance:\n\n- For server software: lock-free is enough. Average case wins.\n- For hard real-time (avionics, medical, audio engines): wait-free is what you need.\n- For everyday code: a well-tuned mutex with a futex backend beats a poorly-rolled lock-free attempt almost every time.',
    },
    {
      level: 'senior',
      question: 'What\'s priority inversion, and how does priority inheritance fix it?',
      answer:
        'Priority inversion is when a **high-priority task ends up waiting on a low-priority task**, which itself can\'t run because medium-priority tasks are preempting it. The high-priority task effectively runs at the priority of the lowest-priority lock holder.\n\nThe minimum recipe: three threads, one mutex.\n\n1. L (low) acquires M, starts critical section.\n2. H (high) wakes, tries to acquire M, blocks.\n3. M (medium) wakes, preempts L because M > L in priority.\n4. As long as M wants to run, L doesn\'t run. L doesn\'t release the mutex. H stays blocked.\n\nH, the highest-priority task, is now starved by M — because L is being starved by M while holding the lock H needs.\n\nThe classic case study: Mars Pathfinder, 1997. A bus manager (high prio), a comms task (medium), and a meteorological task (low) sharing a bus mutex. Pathfinder kept rebooting via watchdog timeout. The JPL fix, uploaded remotely: enable **priority inheritance** on the mutex.\n\n**Priority inheritance**: while a low-priority task holds a mutex that a high-priority task is waiting for, the low-priority task temporarily inherits the high-priority task\'s priority. It runs at the higher priority until it releases the mutex.\n\nNow M can\'t preempt L (L\'s inherited priority is higher than M\'s). L finishes, releases, reverts. H proceeds.\n\nPOSIX: `pthread_mutexattr_setprotocol(attr, PTHREAD_PRIO_INHERIT)`. Linux PI futexes implement it. Most kernels default to "no PI"; you must opt in. The cost is a slightly slower mutex acquire; the benefit is bounded worst-case latency for high-priority work.',
    },
    {
      level: 'senior',
      question: 'Livelock vs deadlock — what\'s the difference, and what causes livelock?',
      answer:
        '- **Deadlock**: threads wait forever on each other. CPU idle. No recovery without intervention.\n- **Livelock**: threads keep doing work but make no progress. CPU at 100%. May or may not recover.\n\nThe corridor metaphor: two people meet; each politely steps aside; they step the same way; bump; step the other way; bump; loop. Each is *doing* something — moving, evaluating, moving — but the system makes no progress.\n\nIn code, the classic livelock is **deadlock avoidance via backoff done wrong**:\n\n```\nfor {\n    if !from.TryLock() { continue }\n    if !to.TryLock() { from.Unlock(); continue }\n    // ... transfer ...\n}\n```\n\nTwo threads doing the same transfer in opposite directions can lockstep: each grabs first lock, fails on second, releases, retries — synchronized. 100% CPU, no progress.\n\nThe fix is **randomized backoff**: sleep a random small amount before retrying. Same trick as Ethernet collision detection — randomness desyncs the threads probabilistically.\n\nOther livelock patterns:\n\n- **Cache stampede**: 1000 threads see the same cache miss, all try to recompute, all hit the DB, all time out, all retry. Fix: request coalescing.\n- **Optimistic-concurrency retry storms**: every transaction conflicts; every retry hits the same conflict. Fix: backoff, partitioning, or fall back to pessimistic.\n- **Circuit breaker oscillation**: half-open lets one probe through; probe succeeds; full traffic resumes; fails; opens; loop. Fix: hysteresis.\n\nDetection signature: **high CPU + flat throughput**. The system looks busy but completes nothing.',
    },
    {
      level: 'senior',
      question: 'Work-stealing — what is it and why is it the standard for modern schedulers?',
      answer:
        'Work-stealing is a scheduling strategy where each worker has its own local queue, and idle workers "steal" from the tail of someone else\'s queue. It\'s the engine inside Go\'s runtime, Tokio, Rayon, Java ForkJoinPool, .NET\'s TPL — basically every modern parallel runtime since the Cilk paper (Blumofe & Leiserson, 1995).\n\nWhy it beats a central shared queue:\n\n- **No central contention.** Each worker pushes/pops its own deque locally. No lock fight on the shared queue.\n- **Cache locality.** A worker that just spawned a task is warm for that task — and runs it next from its own deque.\n- **Random load balancing.** Idle workers pick a random victim and steal; in expectation, load equalizes.\n\nThe trick: **two ends of the deque, different access patterns.**\n\n- **Owner\'s end (LIFO/stack)**: most recently pushed task is popped next. Matches recursive divide-and-conquer; preserves locality.\n- **Thief\'s end (FIFO/tail)**: thieves take the *oldest* task — most likely to be the coarsest, with a big follow-on subtree of work. One steal = lots of work, no further stealing needed.\n\nThe Cilk paper\'s theorem: a computation with total work T₁ and critical path T_∞ runs in expected time T₁/P + O(T_∞) on P processors. Provably near-optimal.\n\nWhat user code can do wrong:\n\n- **Block inside an async task.** Calling a synchronous blocking API parks an entire worker. Use `spawn_blocking` or a separate thread pool.\n- **CPU-heavy work without yields.** Insert `yield_now()` in long loops so the scheduler can rebalance.\n- **Too few tasks.** Work-stealing needs *something* to steal; one giant goroutine doesn\'t benefit.',
    },
    {
      level: 'senior',
      question: 'When would you reach for STM, and why didn\'t it take over?',
      answer:
        'STM (Software Transactional Memory) applies database-transaction semantics to in-process memory. `atomically { … }` opens a transaction; reads and writes are tracked; on commit, the runtime checks for conflicts and either commits atomically or aborts and retries.\n\nThe pitch is **composability**: nesting `atomically` blocks Just Works, unlike nesting lock acquisitions where you have to reason about global lock ordering. STM also gives you `retry` (block until a read changes) and `orElse` (try one transaction, fall back to another) — composable patterns no lock-based scheme supports.\n\nClojure shipped a production STM in 2007; Haskell\'s GHC has the best-known implementation; Akka and ScalaSTM followed.\n\nWhy it didn\'t take over:\n\n1. **I/O can\'t be in a transaction.** If your atomically-block sends an email then aborts, you\'ve still sent the email. STM works only for in-memory state; you need a separate mechanism (Clojure agents, Haskell IO) for side effects.\n2. **Performance overhead.** Every read/write goes through STM machinery — version checks, write-set tracking. 2–10× slower than a well-tuned mutex under low contention.\n3. **Pathological retry loops.** A long transaction that conflicts with frequent small ones can retry forever. Contention managers help but add complexity.\n4. **Hardware support died.** Intel\'s TSX (2013) promised hardware STM; shipped with bugs, was deprecated.\n5. **Simpler models won.** "Don\'t share state at all" (actors, channels) turned out to be a more popular answer than "share via transactions."\n\nWhere STM\'s principles live on: MVCC databases (Postgres, etcd), persistent data structures (Clojure\'s, Immer.js), optimistic concurrency control everywhere — same shape, different scale.',
    },

    // --- staff ---
    {
      level: 'staff',
      question: 'Explain linearizability vs serializability. When does the difference bite?',
      answer:
        'Both promise some form of "behaves as if operations happened in a serial order." The difference is whether real-time ordering is preserved.\n\n**Linearizability** (Herlihy & Wing, 1990):\n- Domain: concurrent objects / data structures.\n- Unit: single operation.\n- Each operation appears to take effect instantaneously at some point between its invocation and its response.\n- **Real-time order preserved**: if op A completed before op B started, A\'s linearization point is before B\'s.\n- Composes: linearizable sub-objects yield a linearizable whole.\n\n**Serializability** (Bernstein et al., 1976):\n- Domain: transactions across multiple objects.\n- Unit: transaction (multi-operation).\n- Some serial order produces the same final state.\n- **No real-time constraint**: T1 may have committed long before T2 started, but the equivalent serial order can be T2-then-T1.\n- Doesn\'t compose across objects.\n\nWhere the difference bites:\n\n**Snapshot isolation** (Postgres default, Oracle default) isn\'t truly serializable. The classic violation is **write skew**:\n\n```\nInitial: on_call = {Alice, Bob}\nT1 reads on_call; sees both there; sets Alice.on_call = false\nT2 reads on_call; sees both there; sets Bob.on_call = false\nFinal: nobody on call. No serial order produces this.\n```\n\nBoth transactions read overlapping data but wrote disjoint sets. Snapshot isolation\'s "no overlap on writes" check missed the conflict. **Serializable Snapshot Isolation** (Postgres `SERIALIZABLE` since 9.1) detects the read-write conflict and aborts one.\n\nFor distributed K/V stores: linearizability is the gold standard for "each operation looks atomic in real time." Spanner\'s "external consistency" is strict serializability — both transactional AND real-time. Most production systems use weaker models for performance and accept the resulting anomalies.',
    },
    {
      level: 'staff',
      question: 'What is the memory model hierarchy, and what does "DRF-SC" mean?',
      answer:
        'Memory models specify what writes from one thread are visible to another, after compiler and CPU reorderings. The hierarchy, from strongest to weakest:\n\n1. **Sequential consistency (SC)** — global total order respecting per-thread program order. Intuitive but expensive.\n2. **TSO (Total Store Order)** — x86. Stores appear in program order to others; loads can pass earlier stores. Strongest of mainstream hardware.\n3. **Weak/RMO** — old ARM, Alpha. Most reorderings allowed.\n4. **ARMv8/RISC-V WMM** — relaxed by default with explicit acquire/release. Modern weak hardware.\n\nWhy not just give everyone SC? Cost. SC requires draining the store buffer on every load — ~20-40ns per fence. The weaker the model, the more the CPU pipeline can do in parallel.\n\n**DRF-SC** = "data-race-free implies sequential consistency." The contract every modern language memory model offers:\n\n> If your program is data-race-free (every access to a shared variable uses a documented synchronization primitive), then the program behaves as sequentially consistent. The compiler and CPU may reorder freely under the hood, but you never observe the reorderings.\n\nUsed in: Java (JSR-133, 2004), C++/C11 (2011), Go, Rust.\n\nThe practical implication: as long as you use mutexes, atomics, channels, or volatile/atomic-annotated variables for cross-thread communication, the model behaves intuitively. The moment you race on plain data, behavior is undefined — and bugs can manifest only on specific hardware (ARM is more aggressive than x86).\n\nThe famous TSO bug: two threads each writing one variable and reading the other; under SC, (r1=0, r2=0) is impossible; under TSO, it\'s observable because store buffers reorder. Code that "works on x86" via TSO accident often breaks on ARM. The fix on any architecture: use atomic operations or memory barriers explicitly.',
    },
    {
      level: 'staff',
      question: 'Walk me through the Lu et al. concurrency-bug taxonomy.',
      answer:
        'Shan Lu et al. (2008), *Learning from Mistakes — A Comprehensive Study on Real World Concurrency Bug Characteristics*. Studied 105 randomly-selected concurrency bugs from MySQL, Apache, Mozilla, OpenOffice. The taxonomy:\n\n- **Atomicity violation (~65%)** — an operation that "should be atomic" interleaves with another.\n  - Single-variable (lost update): `n++` without sync.\n  - Multi-variable (invariant): updating `balance` and `log` separately, another thread sees inconsistent state.\n  - Check-then-act (TOCTOU): `if !cache.has(k); cache.set(k, ...)` — two threads do the same.\n  - Fix: wrap in mutex, or use an atomic compound primitive (`putIfAbsent`).\n\n- **Order violation (~25%)** — a required happens-before is missing.\n  - Initialization order: reader runs before writer initialized state.\n  - Publication ordering: `data = build(); ready = 1;` without barriers.\n  - Signal ordering: result-ready signal fires before the result was actually written.\n  - Fix: add explicit synchronization (signal, await, barrier, atomic publish).\n\n- **Deadlock (~6%)** — circular wait on locks.\n  - Inconsistent lock order across threads.\n  - Self-deadlock on non-recursive mutex.\n  - Lock held during callback that re-acquires.\n  - Fix: lock ordering by ID; tryLock with backoff; release before callback.\n\n- **Other (~4%)** — livelock, starvation, leaks, misc.\n\nThe big lessons:\n\n1. **Atomicity dominates.** Most real concurrency bugs are "forgot to make this multi-step thing atomic."\n2. **Deadlocks are rare** despite textbook fame.\n3. **96% involve just two threads.** Three-thread-only bugs are unusual.\n\nThe practical use: when reviewing concurrent code, look for shared state, identify invariants, check happens-before edges, look for atomic compound operations. Don\'t spend the bulk of your review on deadlock geometry — most bugs aren\'t deadlocks.\n\nModern additions (Taxdc paper, 2016) extend to distributed systems: distributed deadlock and cross-service lost updates. Async-era additions: forgotten `await`, lost cancellation, unbounded `Promise.all`. The original three classes still cover most cases.',
    },
    {
      level: 'staff',
      question: 'You can\'t reproduce a concurrency bug in tests. What do you do?',
      answer:
        'Standard testing only hits "normal" interleavings; concurrency bugs can require specific rare ones. The toolkit, in increasing order of investment:\n\n**1. Stress + race detector in CI.**\n- Run high-volume concurrent operations against the suspect code in a loop.\n- Run with `go test -race`, ThreadSanitizer (C++/Rust), or Java FlightRecorder race detection.\n- These instrument every memory access and flag unsynchronized concurrent ones — *even if no symptom occurred on this run*. The race opportunity is what\'s reported.\n- Most data races are caught here. Run TSan in CI; don\'t skip it.\n\n**2. Schedule fuzzing (Loom, CHESS, PCT).**\n- Replace synchronization primitives with versions that exhaustively explore interleavings.\n- Loom (Rust) is used inside Tokio\'s test suite for low-level sync code.\n- CHESS / PCT (Microsoft) systematically explore interleavings up to a bug-depth bound.\n- Slow but catches rare-interleaving bugs that stress alone misses.\n\n**3. Property-based testing for linearizability.**\n- Collect operation histories from each thread.\n- Check that *some* serial order is consistent with what each thread observed.\n- `porcupine` (Go), `jepsen.checker.linearizable`, `proptest` (Rust) implement this.\n- Especially useful for shared data structures (queues, maps, caches).\n\n**4. Deterministic record/replay (rr, Pernosco).**\n- Run a flaky test under `rr` until it fails.\n- `rr` records the exact schedule; replay it deterministically as many times as you want.\n- Concurrent debugging becomes single-threaded debugging.\n\n**5. Formal model checking (TLA+, SPIN).**\n- Specify the algorithm formally; check safety and liveness properties over all reachable states.\n- Amazon\'s case study: TLA+ found Dynamo/S3 bugs years of stress testing hadn\'t.\n- Use for the core of distributed protocols, consensus, ordering algorithms.\n\nThe pragmatic ladder: stress + race detector is the baseline; add fuzzing/linearizability checks for shared data structures; reach for formal methods on the algorithmic core of critical systems. Production observability with anomaly detection (counter drift, missing updates) catches what slipped through.',
    },
    {
      level: 'staff',
      question: 'A team is choosing a concurrency model for a new chat service. How do you frame the decision?',
      answer:
        'The questions, not the answers, are the framework. Five to ask:\n\n**1. CPU-bound or I/O-bound?**\nChat is I/O-bound — most time is spent waiting on sockets, DB writes, push notifications. So async, channels, or actors. Not raw thread pools.\n\n**2. How much state, and who owns it?**\nEach online user is a stateful long-lived entity: connection, presence, pending-message queue, unread cursors. This strongly favors **actors** (one actor per user) over shared global state with locks.\n\n**3. What\'s the failure model?**\nIf one user\'s actor crashes, the others should be unaffected — and that user\'s session should restart cleanly. This is exactly the actor model\'s "let it crash" + supervisor strength. Erlang/Elixir was designed for telecom (chat is just modern telecom).\n\n**4. How many concurrent things?**\nMillions of online users implies millions of long-lived stateful entities. Per-user OS threads is impossible (memory blow-up). Per-user goroutines is feasible. Per-user actors is best — Erlang processes are KB each; the BEAM scheduler is built for this exact scale.\n\n**5. What does the team know?**\nIf the team is fluent in Erlang/Elixir: ship it. If they\'re Java shop: Akka is the canonical port. If they\'re Go shop: roll a goroutine-per-user pattern with channels for IPC; or use Microsoft Orleans on .NET.\n\nThe answer for chat at scale is **actor model** (often plus some shared infrastructure: presence is a distributed K/V; messages persist in a DB; routing might be via a service mesh).\n\nWhen *not* to pick actors:\n\n- Stateless web API: actors are overkill; async + DB is simpler.\n- Pure CPU compute pipeline: fork-join (Rayon/ForkJoinPool); actors add message-passing overhead.\n- Need ACID transactions across many entities: actor systems don\'t do this naturally; you\'d bolt STM or saga orchestration on top.\n\nThe meta-lesson: concurrency model is per-component, not per-system. A chat service uses actors for per-user state, async for the HTTP front, channels for an internal pipeline, and threads for any heavy CPU-bound encoding work. Pick the right one at each layer.',
    },
  ],
};
