import type { QuestionBank } from './types';

export const bank: QuestionBank = {
  topic: 'paradigms',
  questions: [
    // --- junior ---
    {
      level: 'junior',
      question: 'What\'s a programming paradigm in one sentence — and why should I care?',
      answer:
        'A **paradigm** is a style for organizing a program — a set of ideas about what the building blocks are and how they fit together. OOP says "objects with state and behavior;" FP says "pure functions over immutable data;" declarative says "describe what you want, not how."\n\nWhy you care: paradigms decide *what becomes easy and what becomes hard* in a given piece of code. A user session is naturally OOP-shaped (identity + state over time); a data transformation is naturally FP-shaped (input → output, no identity). Picking the wrong shape doesn\'t fail — it just makes everything harder than it needed to be. Most modern languages are multi-paradigm, so the practical skill is *seeing the right shape* for each piece, not picking one paradigm forever.',
    },
    {
      level: 'junior',
      question: 'What\'s the difference between imperative and declarative code, with an example?',
      answer:
        '**Imperative** tells the computer *how*: step by step, changing state. **Declarative** tells it *what* you want and lets the runtime figure out how.\n\n```ts\n// Imperative — recipe of steps\nconst adults = [];\nfor (let i = 0; i < users.length; i++) {\n  if (users[i].age > 18) adults.push(users[i].name);\n}\n```\n\n```sql\n-- Declarative — describes the result\nSELECT name FROM users WHERE age > 18;\n```\n\nSQL gives the query *planner* freedom to pick indexes, join orders, parallelism — you didn\'t commit to a mechanism. The cost is loss of fine control: if the planner picks a bad plan, you can\'t easily "just write the loop." OOP and procedural are imperative flavors; FP, SQL, HTML, regex, and Prolog are declarative flavors. Most real code mixes both, with declarative where engines outperform you (SQL, layout, build graphs) and imperative where the algorithm itself is the point.',
    },
    {
      level: 'junior',
      question: 'I keep hearing "OOP" — what are its four pillars, really?',
      answer:
        '**Encapsulation, abstraction, inheritance, polymorphism.** That\'s the textbook list — but the two that actually carry the weight in good OOP code are **encapsulation** and **polymorphism**.\n\n- **Encapsulation**: an object owns its state; outsiders interact through methods that maintain invariants. `account.withdraw(50)`, never `account.balance -= 50`. This is the real point of OOP — strip it away and you have a struct.\n- **Polymorphism**: one interface, many implementations. Code depends on a contract (`Notifier`), not a concrete type (`EmailNotifier`), so you can swap implementations without surgery.\n- **Abstraction**: name *what* a type does separately from *how*. Interfaces are the main tool.\n- **Inheritance**: extend one class from another. Useful sometimes, badly overused in 90s/00s code. Prefer composition by default.\n\nMost modern advice: lean hard on encapsulation and polymorphism, use abstraction sparingly (only when there\'s a real boundary), and treat inheritance as a last-resort tool rather than the default.',
    },

    // --- mid ---
    {
      level: 'mid',
      question: 'Why is "composition over inheritance" the modern default?',
      answer:
        'Because inheritance couples subclasses to the *implementation details* of the base — not just its contract. A subclass overrides `increment()`; the base later changes `incrementBy(k)` to update its internal counter directly instead of calling `increment()`, and the override silently stops firing. The base didn\'t change its public contract, but the subclass broke. This is the **fragile base class problem**.\n\nComposition (X *has-a* Y) avoids it: `Logger` holds a `Writer` and forwards to its public methods only. The `Writer`\'s internals can change freely; `Logger` only depends on the interface. You also get runtime flexibility: `new Logger(new FileWriter())` swaps behavior without a new class. Tests get trivial via in-memory fakes.\n\nInheritance still earns its keep for: real `is-a` relationships (`NotFoundError extends HttpError`), frameworks designed for extension (React class components, exception hierarchies), and shallow sealed hierarchies modeling closed sets of subtypes. The rule isn\'t "no inheritance" — it\'s "default to composition; reach for `extends` when there\'s a real reason."',
    },
    {
      level: 'mid',
      question: 'Explain SOLID in a way that doesn\'t sound like a college lecture.',
      answer:
        'SOLID is five named failure modes of OOP code and the habit that avoids each:\n\n- **S — Single Responsibility:** a class that has multiple stakeholders pulling it in different directions (the `UserService` that does auth *and* CSV exports *and* notifications). Fix: split by *reason to change*.\n- **O — Open/Closed:** adding a new variant requires editing an existing function. Fix: polymorphism (`Shape.area()`) so new variants are *new files*, not edits.\n- **L — Liskov Substitution:** subtypes surprise callers expecting the parent. Classic case: mutable `Square extends Rectangle` — `setHeight(4)` after `setWidth(5)` gives 16 instead of 20 because the subtype changed the meaning. Fix: subtypes preserve the parent\'s contract.\n- **I — Interface Segregation:** a fat interface forces clients to depend on methods they don\'t use. Fix: split contracts by client; let one class implement multiple narrow interfaces.\n- **D — Dependency Inversion:** high-level logic hard-codes low-level details (`OrderService` builds its own `PostgresUserRepository`). Fix: depend on interfaces, inject implementations.\n\nIt\'s a diagnostic vocabulary, not a religion. Code that\'s easy to change usually satisfies it whether or not anyone planned it that way.',
    },
    {
      level: 'mid',
      question: 'What\'s a pure function, and why does it matter even if I don\'t do "FP"?',
      answer:
        'A **pure function**: same input → same output, no side effects (no mutation of outside state, no I/O, no hidden randomness). `(a, b) => a + b` is pure; `() => Date.now()` is not; anything that calls `console.log` or mutates a global is not.\n\nPurity matters in any paradigm because pure functions give you several free superpowers at once:\n- **Testable without setup** — pass input, assert output, no mocks.\n- **Cacheable** — `memoize(f)` is a one-liner that works for any pure `f`. React\'s `useMemo`/`useCallback` rely on this.\n- **Parallelizable safely** — no shared state, no races.\n- **Easier to debug** — bug reproduces with just the inputs; paste into a test, fix in five minutes.\n- **Honest signatures** — `discount(price, percent): number` can\'t lie about doing I/O.\n\nThe pragmatic move in any codebase is "functional core, imperative shell": keep business logic as pure functions over plain data, push I/O (DB, HTTP, files, clock) to the boundary. You don\'t need Haskell — a TypeScript codebase that does this gets most of the win.',
    },
    {
      level: 'mid',
      question: 'Why "depend on interfaces, not concrete classes" — and where does it stop being useful?',
      answer:
        'Depending on an interface decouples a caller from the specific implementation. `OrderService` that constructs its own `PostgresUserRepository` is welded to Postgres: tests need a real DB, swapping stores is a migration project, and the class mixes business logic with infrastructure choices. `OrderService` that takes a `UserRepository` interface as a constructor argument is testable with an in-memory fake, swappable in production, and ignorant of the storage choice.\n\nThat\'s the **Dependency Inversion Principle** (the D in SOLID) and the heart of dependency injection. You don\'t need a DI framework — passing a constructor argument *is* DI.\n\nWhere it stops being useful: **pass-through interfaces** with one implementation forever, no test fake worth naming, just an indirection layer because "we might need it someday." That\'s YAGNI; you pay the readability tax now and earn the benefit never. Rule of thumb: introduce an interface when you have a real second implementation (or a test fake elaborate enough to deserve a name). One class with no second implementation in sight doesn\'t need a separate `IFoo`.',
    },
    {
      level: 'mid',
      question: 'My team says "immutability everywhere." Is that always faster to reason about, even when it allocates more?',
      answer:
        '"Easier to reason about" usually — yes. "Faster" — depends.\n\nThe wins of immutability are real: no aliasing surprises (pass a value anywhere, it can\'t mutate under you), safe concurrency without locks, trivial undo / time-travel debugging, cheap reference-equality short-circuits (React\'s reconciler relies on this).\n\nThe cost — extra allocations — is mostly mitigated by **persistent data structures** (Clojure\'s vectors, Immutable.js, Immer). They use trees with structural sharing: updating one element in a million-item vector copies ~log₃₂(1,000,000) ≈ 4 nodes, not a million. For typical app workloads, they\'re within a small constant factor of mutable equivalents and win on concurrency.\n\nWhere immutability actually loses: hot inner loops (graphics, audio, parsers, codec internals) where allocating per iteration shows up in profiles. There, in-place mutation of a buffer beats persistent structures by an order of magnitude.\n\nThe useful rule: **values are immutable; entities have controlled mutation through encapsulation**. A `Money` is a value (no identity, immutable). A `BankAccount` is an entity (identity, encapsulated mutable state). Confusing the two ("version 47 of this connection") leads to fighting either the language or the domain.',
    },
    {
      level: 'mid',
      question: 'JavaScript "classes" — are they classes or just sugar over prototypes?',
      answer:
        'Sugar over prototypes. JS is prototypal underneath: every object has a `[[Prototype]]` pointer; property lookups walk that chain. `class Foo {}` creates a constructor function with `Foo.prototype` set up correctly, and `extends` wires the prototype chain.\n\nYou can see the prototype model when you `Object.getPrototypeOf(instance)`, when you patch `Array.prototype` and affect every array in the program, or when `this` does something surprising because dispatch is dynamic at the call site.\n\nWhat this means practically:\n- `this` is **dynamic** — depends on how the function is called, not where it\'s written. `setTimeout(obj.method, 100)` loses `this` because the call site is `setTimeout`\'s, not `obj`\'s. Arrow functions, `.bind`, or `() => obj.method()` fix it.\n- **Hidden classes** in V8 recover class-like performance: V8 infers a hidden "shape" from property additions and optimizes accordingly. This is why adding properties in a consistent order matters for perf.\n- **Real privacy** uses `#field` (runtime-enforced); `private` in TypeScript is compile-time only and disappears at runtime.\n\nClass syntax is fine — most JS today uses it. Just remember it\'s a UX over prototypes, not a different model.',
    },
    {
      level: 'mid',
      question: 'What does "coupling" actually mean — and when is it too high?',
      answer:
        '**Coupling** is how much modules depend on each other. The ranked forms (worst to best, Constantine\'s ladder):\n\n1. **Content coupling** — reaching into another module\'s internals (private fields, monkey-patching). Touching one breaks the other in subtle ways.\n2. **Common coupling** — shared global mutable state. Anyone can change it; no one owns it.\n3. **Control coupling** — A passes B a flag controlling which branch B executes. B isn\'t a black box anymore.\n4. **Stamp coupling** — A passes B a whole big object; B uses two fields. B now depends on the whole shape.\n5. **Data coupling** — A passes B exactly the values it needs. Clean.\n6. **Message coupling** — A sends B a message via a well-known interface. The loosest useful form.\n\n**Too high** = the grep test fails: change file A, you need to update five unrelated files. Or: features that change together always touch multiple modules, suggesting the seam is in the wrong place. Or: new teammates can\'t guess where a change goes without institutional knowledge.\n\nLowering coupling is mostly the *cohesion question in disguise*: lines drawn between modules are wrong when the things that change together don\'t live together. Most refactoring is moving those lines.',
    },
    {
      level: 'mid',
      question: 'What\'s the difference between OOP-style and FP-style polymorphism?',
      answer:
        'OOP usually means **subtype polymorphism**: a subclass/subtype can be used where the parent is expected. `notifier.send(msg)` works whether `notifier` is `EmailNotifier` or `SlackNotifier`. Dispatch is dynamic via a vtable.\n\nFP usually means **parametric polymorphism** (generics): one function works for any type, with the type as a parameter. `function identity<T>(x: T): T { return x }` — `T` is opaque; the function literally can\'t do anything to it except shuffle it around. This is called *parametricity*, and it\'s what lets the compiler prove things about your generic code.\n\nThere\'s also **ad-hoc polymorphism** (operator/method overloading, Haskell typeclasses, Rust traits): the same operation name, different implementation per type. `1 + 2` (number addition) vs `"a" + "b"` (string concat) is the simplest example. Modern languages mix all three.\n\nThe key practical difference: subtype polymorphism is open to new *types* (add a `SmsNotifier`; nothing else changes). Tagged unions + pattern matching are open to new *operations* (add `perimeter` to all shapes in one switch, not N classes to edit). Pick which axis you add things to more often, and that\'s the right tool.',
    },

    // --- senior ---
    {
      level: 'senior',
      question: 'A junior dev wraps every domain function in a class with one method. What\'s wrong, and what\'s the underlying confusion?',
      answer:
        'Nothing\'s syntactically wrong — a class with one method is a function in costume. The confusion is mistaking the *language feature* (classes) for the *paradigm* (OOP). OOP\'s value is **encapsulation** (an object owns its state and invariants) and **polymorphism** (callers depend on interfaces, not concretes). A one-method class with no fields gives you neither — it just adds a constructor, a `this`, and an extra layer of `new SomethingService().doIt(...)` ceremony.\n\nWorse downstream: tests have to instantiate the class; types get noisier; a reader hunting for "where\'s this logic?" goes through one more file than needed; refactoring across N such service classes is harder than across N plain functions.\n\nThe rule that helps: **classes earn their existence by having state or polymorphism.** If the class has fields and methods that maintain invariants — class. If the class is polymorphic and callers depend on the interface — class. If it\'s just one function pretending to be more — make it a function in a module.\n\nThis isn\'t anti-OOP. It\'s "don\'t use OOP\'s syntax when its semantics aren\'t earning anything."',
    },
    {
      level: 'senior',
      question: 'A teammate proposes a Haskell-style monadic effect system in our TypeScript codebase. How do you reason about that decision?',
      answer:
        'The pure technical case can be strong: effects in types (`Effect<DBError | NetworkError, User>`) make impurity visible at the function signature, give you compositional error handling, and unlock features like automatic retries, dependency injection, and resource scoping. Effect-TS and similar libraries are genuinely good engineering.\n\nThe forces against it are organizational:\n\n1. **Onboarding cost.** New hires learn the language; *then* they learn the effect system. That\'s months, not weeks, of unproductivity. Multiply by team size and turnover.\n2. **Tooling cost.** Stack traces through deep effect compositions are noisier; debuggers don\'t natively show effect state; AI completions are weaker on niche patterns.\n3. **Hiring filter.** "Comfortable in Effect-TS" is a smaller pool than "comfortable in TypeScript." The filter may help or hurt depending on the team.\n4. **Reversibility.** Effect systems thread through the codebase — once 30% of functions return `Effect<...>`, removing it is a multi-quarter project.\n\nThe decision questions: *Does our problem domain actually benefit?* (Lots of cross-cutting concerns like retries, tracing, resource scoping — yes. CRUD service — meh.) *Is the team capable and bought in, not just curious?* *Are we willing to live with this for years?*\n\nThe boring middle — keep most code pure, push I/O to the edges, use Result/Either types where it earns its keep — captures 70% of the win at 10% of the cost. Reach for a full effect system when 70% isn\'t enough and the team can sustain it.',
    },
    {
      level: 'senior',
      question: 'When does inheritance actually earn its keep over composition?',
      answer:
        'Three cases:\n\n1. **Real "is-a" relationships in shallow hierarchies.** Exception hierarchies are the canonical example: `NotFoundError extends HttpError extends Error`. The relationship is genuine, the hierarchy is one or two levels, and the win is `catch (e instanceof HttpError)` dispatching uniformly. Catching by base type is *the* feature that inheritance gives you cleanly.\n\n2. **Frameworks designed for extension.** When the framework\'s contract is "subclass this and override these methods," do that — React class components (pre-hooks), Android `Activity`, JUnit base classes, Spring controllers. The base is engineered for it: protected surface is small, documented, stable. Fighting the framework with composition here is worse.\n\n3. **Sealed hierarchies / closed sets of subtypes.** Languages with sealed classes (Kotlin, Scala, Java records + sealed) let you model `Result<T> = Ok<T> | Err` cleanly. Pattern matching on these is often clearer than the Visitor pattern.\n\nWhere it doesn\'t earn its keep is the 90% case: **code reuse**. If you want to share helpers, share helpers — composition + delegation gives you the same reuse with weaker, healthier coupling. The fragile base class problem isn\'t theoretical; it\'s the failure mode every long-lived class hierarchy eventually hits.\n\nThe shorthand: **inheritance for subtyping, composition for reuse.** When you find yourself reaching for `extends` purely to avoid duplicating code, that\'s the signal to compose instead.',
    },
    {
      level: 'senior',
      question: 'How do you tell if a problem is "OOP-shaped" or "FP-shaped"?',
      answer:
        'Ask one question: **does the thing have identity, or is it a value?**\n\nA *value* is fully described by its contents. Two `Money(100, "USD")` instances are the same `Money`; you don\'t care which is which. Dates, points, configs, request bodies, validation results — values. These are FP-shaped: immutable, transformed by pure functions, equality is structural.\n\nAn *entity* has identity that persists across changes. Two `User` instances with the same fields are still different users — they have IDs. A `Connection`, a `Session`, an `Order` in flight — entities. These are OOP-shaped: encapsulated mutable state, lifecycle (`connect → use → close`), equality is by identity.\n\nA second question to confirm: **does state evolve over time, or is the computation a one-shot transformation?** Long-lived state → OOP. Input-to-output → FP.\n\nMost features have *both*. A checkout has an `Order` (entity, OOP-shaped: id, status, lifecycle), `LineItem`s (often values, FP-shaped), a `total` calculation (pure function, FP-shaped), and a payment confirmation (event-driven). Each piece picks the shape that fits.\n\nThe failure mode is forcing the wrong shape: classes wrapped around pure functions that have no state, or values modeled as long-lived objects that are immutable but pretend to be entities. When you find yourself fighting the paradigm, recheck which shape the problem actually is.',
    },
    {
      level: 'senior',
      question: 'Walk me through how a query planner is a logic-programming engine in disguise.',
      answer:
        'A SQL query is a *declarative specification* of a relation you want. The planner\'s job is to find an execution strategy — an *answer* in the logic-programming sense — that produces that relation.\n\nThe correspondence:\n\n- **Tables ≈ facts.** Each row is a fact: `users(id=1, name="Ada", country="US")`.\n- **Joins ≈ rules.** `SELECT u.name FROM users u JOIN orders o ON o.user_id = u.id` is a rule: "for each user `u` and order `o` where `o.user_id = u.id`, return `u.name`."\n- **WHERE clauses ≈ constraints** that solutions must satisfy.\n- **The planner ≈ a search engine** that picks an execution order (which table to scan first, which join algorithm to use, whether to use an index) to minimize cost.\n\nThe planner does cost-based search: try plans, estimate row counts using statistics, pick the cheapest. It\'s heuristic logic programming with row counts as the cost metric. Recursive CTEs make this explicit — they\'re literally Datalog with SQL syntax.\n\nThe deeper insight: anywhere you see "the system figures out a valid execution from a declarative spec," there\'s a logic-programming engine in the basement. Type inference, package resolvers (npm, Cargo, modern pip), static analyzers, constraint-based layout engines — all the same family. Recognizing this lets you reach for a solver (or a real Datalog) when a problem is *really* a constraint problem, instead of writing the search yourself.',
    },
    {
      level: 'senior',
      question: 'What\'s the relationship between event-driven and reactive paradigms? Are they the same thing?',
      answer:
        'Related but not the same.\n\n**Event-driven** is about *discrete occurrences* dispatched to handlers. The runtime owns the control loop; your code is a bag of registered handlers (`onClick`, `onRequest`, `onMessage`). The shape: wait → react → wait. Examples: browser DOM events, Node\'s libuv loop, GUI frameworks, message-driven backends, game loops.\n\n**Reactive** is about *values changing over time*, with derived values automatically kept in sync. The shape: declare relationships (`doubled = count * 2`); the engine propagates updates through the dependency graph. Examples: signals (Solid, Preact Signals, Vue refs), streams (RxJS), spreadsheets, React\'s render model.\n\nThe overlap: both involve "something changes; downstream things react." But:\n- Event-driven is *low-level mechanism* — handlers, queues, dispatch.\n- Reactive is *high-level declarative model* — the dependency graph manages itself; you don\'t write listeners.\n\nA modern UI uses both: events (clicks, keypresses) flow in via event-driven mechanisms; the framework converts them to state changes; reactive primitives (signals/hooks) propagate to derived values and the rendered DOM. Streams (RxJS-style) sit in the middle — events as first-class values you can transform with functional operators.\n\nThe practical takeaway: when you find yourself manually wiring "if A changes, update B, C, and D," you\'re reinventing reactive on top of event-driven. Reach for a reactive primitive (signals, computed) and stop hand-rolling subscriptions.',
    },
    {
      level: 'senior',
      question: 'How do you avoid SOLID becoming "abstraction theater" — interfaces and indirection that don\'t help anyone?',
      answer:
        'The pattern: a team reads about SOLID, sets a policy ("every class behind an interface"), and ends up with `IUserService → UserService → IUserRepository → UserRepository` where every interface has exactly one implementation and every method forwards unchanged. You\'ve paid the readability tax for indirection and gotten zero of the benefits (testability, swappability, decoupling) because none was needed.\n\nThe defenses:\n\n1. **Introduce abstractions when you have a real second implementation.** One real class + one in-memory test fake = worth an interface. One real class with no second in sight = a class. Refactor *to* the interface when the second one shows up; that\'s cheap.\n2. **Apply Open/Closed reactively, not predictively.** When you add the second variant of a thing, refactor to polymorphism so the third is easy. Designing for extension points you\'ll never use is overengineering.\n3. **Watch for pass-through layers.** A `UserService` whose every method just calls a same-named `UserRepository` method, with no logic, no invariants, no transformation. Delete it. It\'s a class for the sake of a class.\n4. **Watch for parameter coupling.** A constructor taking 8 collaborators is doing 8 jobs. The class isn\'t cohesive; the SOLID solution is to split by *which collaborators it uses together*, not to add more interfaces.\n5. **Measure by change friction, not by SOLID compliance.** Code that\'s easy to change usually satisfies SOLID by accident. Code that\'s SOLID by pattern but hard to change has missed the point.\n\nThe one-line rule: **SOLID is a diagnostic vocabulary, not a syntactic mandate.** Use it to name failure modes you\'re hitting, not to manufacture indirection you don\'t need.',
    },

    // --- staff ---
    {
      level: 'staff',
      question: 'A team wants to rewrite a stable Java service in Rust + functional style. How do you frame the decision?',
      answer:
        'I separate three forces and reason about each:\n\n**1. Technical fit.** What is the rewrite *actually* solving? Specific symptoms: GC pauses hurting tail latency, memory footprint too high, FFI to a native lib being painful, type system not catching certain bug classes. If the answer is "Rust is nicer to write," that\'s not a business case. If it\'s "our P99 tail latency is dominated by GC and we\'ve exhausted JVM tuning," that\'s real.\n\n**2. Team and organizational cost.** Rust + functional style is a steep ramp. Onboarding new hires is months, not weeks. The existing team needs deep buy-in, not "we tried it on a weekend project." Hiring filters narrow. Tooling (debuggers, profilers, AI completion quality, library ecosystem) is mature for Rust but thinner than the JVM\'s. If we lose half the team to the learning curve or to competing offers, the rewrite is net-negative regardless of how nice the code is.\n\n**3. Reversibility and blast radius.** A rewrite is months to a year of opportunity cost; during it, the team isn\'t shipping features. The "rewrite from scratch" failure mode (Joel Spolsky, 2000) is real: by the time the rewrite is done, the original has acquired new features the rewrite hasn\'t, and the team is now maintaining two systems. Strangler-fig migration (one service at a time, behind a router) is the lower-risk path if the rewrite is actually justified.\n\nMy framing for the staff conversation: *describe the specific symptoms; estimate the cost in engineer-months; ask what features we won\'t ship during the rewrite; pilot it on a real (small, contained) service first.* If after the pilot the team is still committed, the symptoms are real, and the cost math holds — go. Otherwise the boring answer (incremental wins on the existing stack) is usually right.\n\nThe meta-point: paradigm and language migrations are *organizational* decisions wearing technical clothes. The technical case is necessary but rarely sufficient.',
    },
    {
      level: 'staff',
      question: 'You\'re designing a greenfield codebase for a new product. What\'s your paradigm default, and how would you defend deviating from it?',
      answer:
        'For a typical business-software product in 2026, my default is **TypeScript** (or Kotlin/C#/Rust depending on perf and domain) with this shape:\n\n- **OOP at the service / module boundary.** Dependency injection via constructor args. Boring, legible, every engineer can read it.\n- **FP-style domain code inside.** Immutable values, pure functions, discriminated unions for state, pattern matching where supported. Functional core, imperative shell.\n- **Declarative where engines exist.** SQL for data, regex for patterns, IaC (Terraform/k8s) for infra, declarative UI frameworks (React with signals or Solid/Svelte).\n- **Event-driven** at integration edges (queues, webhooks).\n- **Reactive primitives** for UI state and any value-changes-over-time problem.\n- **Concurrency** via async/await + structured concurrency, not raw threads + locks.\n\nThis isn\'t the *coolest* stack. It\'s the one with the lowest hidden taxes: hiring market is large, AI tooling is strong (training data lives here), library ecosystem is huge, onboarding is fast, paradigm choices are within mainstream practice, and the *paradigm cost* is low so the team can spend its complexity budget on the *problem*, not on the paradigm.\n\n**When I\'d deviate:**\n- **Domain dominated by algebraic reasoning** (compilers, type checkers, query optimizers, theorem provers) → Haskell/OCaml/Rust + functional style. The match between paradigm and problem is so strong that mainstream choices become a tax.\n- **Domain dominated by hard concurrency** (telecom, multiplayer game servers, distributed coordination) → Erlang/Elixir actors or strict Go CSP. The actor model isn\'t marketing; it really does eliminate whole bug classes.\n- **Domain dominated by hard performance** (game engines, HFT, databases, codecs) → C/C++/Rust with data-oriented design. OOP and FP both lose to a tight procedural loop with the right data layout.\n- **Strong existing team expertise** (a team of senior FPers, or senior Rustaceans) → match the team. Team capability dominates paradigm choice.\n\nThe meta-principle: **paradigm choice is an org-design decision.** Pick the boring middle by default; deviate only when there\'s a specific class of problem that justifies the deviation *and* a team that can sustain it for years. Code quality fundamentals (encapsulation, narrow interfaces, immutability where you can swing it, small modules) matter more than the paradigm label — get those right and the choice of "OOP vs FP" becomes a label rather than a verdict.',
    },
  ],
};
