import type { QuestionBank } from './types';

export const bank: QuestionBank = {
  topic: 'performance',
  questions: [
    // --- junior ---
    {
      level: 'junior',
      question: 'What\'s the difference between latency and throughput, and when do they trade off?',
      answer:
        '**Latency** is how long one request takes, end-to-end. **Throughput** is how many requests per second the system finishes. Different units, different measurements.\n\nFor an idle system serving one request at a time, throughput = 1/latency. The interesting regime is concurrent load, where Little\'s Law applies: `L = λ × W` — concurrency = throughput × latency.\n\nThey\'re *often* not trade-offs. A faster algorithm, smaller payload, warmer cache — all improve both. The real trade-offs show up at queueing time:\n\n- **Batching** improves throughput, hurts per-request latency. Each request waits for the batch to fill.\n- **Higher queue utilization** improves throughput, hurts latency. The (1−ρ) term in queue wait explodes near saturation.\n- **More queueing depth** improves throughput, hurts latency.\n\nRule: throughput is a budget you spend on **headroom**, not a target you should fully consume. At ρ=0.95, latency is hyperbolic; small spikes turn into outages.',
    },
    {
      level: 'junior',
      question: 'Why does an O(N²) algorithm sometimes ship to production without issue, but other times causes outages?',
      answer:
        'Because Big-O is meaningless without knowing what N is. "O(N²) is slow" is wrong; "O(N²) where N can grow without bound is dangerous" is right.\n\nO(N²) is fine when:\n\n- N is bounded by physics or domain rules. "Pieces on a chess board" is capped at 32.\n- N is bounded by the platform. "Items on a screen" might be capped at 200.\n- The constant factor is small and N stays modest. Insertion sort beats quicksort under N≈30.\n\nO(N²) is dangerous when:\n\n- **N is user-controlled.** "It\'s just the number of teams a user is in" — until a power user joins 5,000 teams.\n- **N grew silently.** Code written when N was 50, now N is 50,000.\n- **The function is hot.** A nested loop of N=20 over 10,000 requests/sec is fine; N=200 is 4×10⁹ ops/sec.\n\nThe right framing isn\'t "is this algorithm slow?" but "where does N come from, and what bounds it?" If N is user-controlled, your algorithm needs to be at least O(N log N).',
    },
    {
      level: 'junior',
      question: 'How do you tell where time is going in a slow program?',
      answer:
        'Profile. Don\'t guess. Three things to do, in order:\n\n1. **Check CPU vs wall-clock time first.** If wall ≫ CPU, the program is waiting (I/O-bound), not computing (CPU-bound). A CPU profiler on a wait-heavy program just shows the wait syscall.\n2. **Pick a sampling profiler.** Lower overhead than instrumentation, safe to run on prod. Tools: `perf` + flame graph, `async-profiler` (JVM), `go tool pprof`, Pyroscope.\n3. **Read the flame graph by width at the top.** Wide bars near the top = hot leaf functions. Wide bars near the bottom (main) tell you nothing — main *should* be wide.\n\nKey distinction: **self time** vs **total time**. Sort by total time to find the root of expensive call chains; self time alone surfaces things like malloc that are called from the real bug.\n\nBefore profiling: reproduce the slowness reliably, form a hypothesis, measure a baseline. A profile without a hypothesis is just a flame graph to stare at; one tested against a hypothesis is a tool.',
    },
    {
      level: 'junior',
      question: 'Walk me through the N+1 query bug and a few ways to fix it.',
      answer:
        'You write code that looks linear: fetch a list, then in a loop fetch related data for each item.\n\n```js\nconst users = await db.query(\'SELECT * FROM users\');     // 1 query\nfor (const u of users) {\n  u.posts = await db.query(\'SELECT * FROM posts WHERE user_id = ?\', u.id);  // N queries\n}\n```\n\nFor 100 users that\'s 101 queries. Even at 2ms each, you\'ve burned 200ms in round-trip overhead. The CPU was idle for most of it.\n\nFixes:\n\n1. **Eager loading / join**: `SELECT u.*, p.* FROM users u LEFT JOIN posts p ON p.user_id = u.id`. One query. ORM equivalents: Django `select_related`, Sequelize `include`, Hibernate `JOIN FETCH`.\n2. **Batch with IN(...)**: Collect IDs first, then `WHERE user_id IN (?, ?, ...)`. Two queries instead of N+1.\n3. **DataLoader pattern**: Collect every `load(id)` within an event-loop tick and issue one batched query. Standard fix for GraphQL N+1.\n\nDetection: log every query in dev with the call site; assert query counts in tests; APM tools auto-detect "N similar queries in one request." The bug hides until you have realistic data — fixture-sized test data doesn\'t expose it.\n\nThe same pattern appears with HTTP: one user request triggers N downstream API calls. Same diagnosis, same fixes (bulk endpoint, batched call, `?include=...`).',
    },
    {
      level: 'junior',
      question: 'What does "premature optimization is the root of all evil" actually mean? When isn\'t it premature?',
      answer:
        'Knuth\'s full quote matters: "We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%."\n\nThe operative word is **noncritical**. Knuth isn\'t saying "don\'t optimize." He\'s saying don\'t optimize without knowing where the critical 3% is.\n\n**Premature** (the bad thing):\n- Inlining functions before profiling.\n- Replacing readable code with bit tricks before measuring.\n- "What\'s faster, X or Y?" when both run in nanoseconds and the function is called once.\n- Optimizing a function that\'s 0.4% of runtime.\n\n**Not premature** (just design):\n- Picking a hash map over a linear scan at design time. Same effort to write.\n- Adding pagination on a list endpoint — unbounded lists are a known footgun.\n- Streaming when payloads can be huge.\n- Using the right data structure for the access pattern.\n\nThe reliable filter: **if the optimization makes the code harder to read or change, you need a measurement to justify it.** If it costs nothing in readability, it\'s just design, not optimization.\n\nIn the real world, 30-60% of a service\'s CPU is the DB driver, 10-20% is JSON serialization, and the rest is split. Optimizing your business logic by 2× when it\'s 20% of runtime moves the total by 10%. Knowing where time goes matters more than micro-optimizing.',
    },
    {
      level: 'junior',
      question: 'What\'s the basic idea behind caching, and what kinds of bugs does it cause?',
      answer:
        'A cache is a smaller, faster copy of a slower source of truth. It works because real workloads have three properties: **temporal locality** (you\'ll touch the same thing again soon), **spatial locality** (you\'ll touch nearby things), and **heavy-tail popularity** (a small fraction of data accounts for most traffic).\n\nThe gain equation: `gain = hit_rate × time_saved − miss_overhead − invalidation_cost − memory_cost`.\n\nFour patterns:\n- **Cache-aside**: app checks cache, misses fetch from DB and populate. Most common; app owns consistency.\n- **Read-through**: cache layer fetches on miss; app only talks to cache.\n- **Write-through**: writes go to both cache and DB synchronously.\n- **Write-back**: writes go to cache only, async flush to DB.\n\nThe bugs:\n\n1. **Cache invalidation is famously hard.** Wrong invalidation = serving stale data forever. Three approaches: TTL (eventual), explicit invalidate on write, event-based via CDC. TTL is simplest; explicit invalidate is fragile; event-based is complex.\n2. **Stampede / thundering herd.** Popular entry expires; 1000 concurrent requests miss and hammer the DB. Mitigations: single-flight locking, probabilistic early expiration, stale-while-revalidate.\n3. **Forgetting to invalidate on write paths.** Now reads stay stale.\n4. **Unbounded growth.** No eviction policy → OOM. Default to LRU with a size cap.\n5. **Low hit rate.** A cache that misses 90% of the time is overhead. Measure before celebrating.',
    },
    // --- mid ---
    {
      level: 'mid',
      question: 'How do you decide if a workload is CPU-bound, I/O-bound, or memory-bound?',
      answer:
        'The cheap signal first: **compare CPU time to wall-clock time** (e.g., `time my_program`).\n\n- `wall ≈ CPU` → CPU-bound (single thread).\n- `wall < CPU` → CPU-bound, multi-threaded (CPU sums across cores).\n- `wall ≫ CPU` → I/O-bound. Most time is waiting.\n\nThen there\'s **memory-bound** — a hidden third case where CPU is busy but stalled waiting on cache misses. Symptom: CPU at 100% but IPC (instructions per cycle) below 1.0 in `perf stat`. The work is fine; the CPU is waiting for DRAM.\n\nThe implications for scaling are different:\n\n- **CPU-bound**: more cores or faster CPU help. Async doesn\'t. Profile with a sampling CPU profiler; look for algorithmic wins.\n- **I/O-bound**: async/event-loop helps massively (threads no longer block on wait). More CPUs don\'t help. Trace requests end-to-end; look at connection pools, retries, slow downstreams.\n- **Memory-bound**: more cores don\'t help; you\'re bottlenecked on memory bandwidth. Fix by improving data layout (struct-of-arrays, sequential access, smaller working set).\n\nThe most common mistake: throwing async at CPU-bound work. Async means "yield while waiting." There\'s nothing to wait on if you\'re computing. You just hog the event loop.\n\nReal services are mixed: a request handler parses JSON (CPU), hits Redis (I/O), queries the DB (I/O), serializes the response (CPU). The right design overlaps I/O while running CPU work on a thread pool sized to cores.',
    },
    {
      level: 'mid',
      question: 'What is a flame graph and how do you read one without fooling yourself?',
      answer:
        'A flame graph aggregates stack samples from a profiler. Width = fraction of total CPU time in that function. Y-axis = stack depth. Each horizontal bar is a function; bars stack vertically when one function calls another.\n\nThe critical conventions:\n\n- **x-axis is NOT time.** It\'s alphabetical or aggregation order. Adjacent bars at the leaf aren\'t sequential in execution; they\'re siblings sorted for display.\n- **Wide bars near the top** are hot leaf functions and the candidates for optimization.\n- **Wide bars near the bottom** (`main`, event loop) are useless to read — they\'re wide because they parent everything.\n\nHow to read in 30 seconds:\n\n1. Look at the top of the flame.\n2. Find unexpected wide bars. "Why is `JSON.stringify` 30% of my request?"\n3. Click to zoom into that subtree to see *where* it\'s called from.\n4. Estimate the win: a 25% bar can yield at most a 25% improvement, and only if you eliminate it.\n\nMistakes to avoid:\n\n- **Mistaking deep stacks for "slow."** A tall narrow tower might be 1% of runtime.\n- **Optimizing the bottom.** You can\'t optimize `main`.\n- **Treating self time as the only signal.** Sort by total time to find roots; self time surfaces utility functions called from real bugs.\n- **Forgetting it\'s sampled.** Functions that run a million times very fast might not show up; functions that run once but slowly are easy to find.\n\nVariants: **off-CPU flame graph** (samples while threads are blocked — finds lock contention and I/O waits), **differential flame graph** (color by delta between two runs — finds regression-introducing changes).',
    },
    {
      level: 'mid',
      question: 'Why does connection pool size matter and how should you pick it?',
      answer:
        'Opening a TCP+TLS connection is expensive (5-50ms per new connection). A pool keeps a small set of warm connections and hands them out to threads/requests. Without pooling, every query pays the setup cost; with pooling, only the first does.\n\nThe non-obvious rule: **bigger pools are usually worse**.\n\nPostgres typically struggles past ~200 active connections per node (each is a process). MySQL is friendlier but capped. If 10 app instances each have `max=100`, that\'s 1000 potential connections to a single DB — the DB collapses. The DB has its own connection limits and per-connection cost; adding pool capacity beyond what the DB handles healthy just shifts the queue from your app to the DB and makes the DB slower.\n\nPgBouncer\'s historical rule: sweet spot is around `2 * cores + spindles` on the DB side, divided across all clients. For a 16-core DB, ~40 active connections *total* across the whole fleet.\n\nPractical guidance:\n\n- Start small. `max=10` per instance is fine for most services.\n- Watch pool wait time and queue length. Non-zero p95 wait time = under-provisioned *or* DB is bottleneck.\n- Add a shared pooler (PgBouncer, ProxySQL) for high concurrency. The pooler holds N connections to DB and multiplexes M >> N client connections.\n\nFailure modes worth knowing:\n\n- **Pool exhaustion from slow queries** — set `statement_timeout` so one bad query doesn\'t hold a connection for 30s.\n- **Connection leaks** from missing `finally`/`with` blocks — always use scoped borrow idioms.\n- **Stale connections** from network/LB closures — validate periodically or detect on use and retry.\n- **One slow dependency holding all connections** — separate pools per dependency.',
    },
    {
      level: 'mid',
      question: 'How does HTTP caching actually work, and which directives matter?',
      answer:
        'Every cache between client and origin asks two questions per request:\n\n1. Can I serve from cache without asking origin? (**fresh**)\n2. If not, can I avoid sending the full response again? (**stale-but-validatable**)\n\n`Cache-Control` directs every cache. The ones that matter:\n\n- **`max-age=N`**: fresh for N seconds.\n- **`s-maxage=N`**: like max-age but only for shared caches (CDNs); browser ignores.\n- **`public` / `private`**: shared cache may store / only end-user\'s browser may store.\n- **`no-cache`**: **may store, but must revalidate before serving.** Not "don\'t cache."\n- **`no-store`**: don\'t store at all. What people usually mean when they say "no-cache."\n- **`immutable`**: content never changes; don\'t revalidate.\n- **`stale-while-revalidate=N`**: serve stale while refreshing.\n- **`stale-if-error=N`**: serve stale on 5xx.\n\nValidators (`ETag`, `Last-Modified`): when stale, the cache asks origin "is your copy still fine?"; origin returns 304 if unchanged. Saves bandwidth on revalidate.\n\nKiller pattern: **hashed-URL caching**. Build emits `main.4f3a.js`; server sets `Cache-Control: public, max-age=31536000, immutable`. The asset can be cached for a year because the URL itself encodes the version.\n\nCommon bugs:\n\n- **Caching authenticated responses as `public`** — leaks user data via the CDN.\n- **`Vary: User-Agent`** — catastrophic cardinality; every UA is a new cache entry.\n- **`Vary: Cookie`** — same; every cookie is unique.\n- **HTML with long TTL** — deploys don\'t roll out; users see old HTML pointing at old assets.\n- **`stale-while-revalidate` without `max-age`** — serves stale forever.',
    },
    {
      level: 'mid',
      question: 'When should you memoize, and what bugs does memoization cause if you\'re not careful?',
      answer:
        'Memoize when **all four** hold:\n\n1. The function is **pure** — same inputs always give same outputs, no side effects the cache would hide.\n2. Inputs are **hashable and small** — a function taking a 5MB object has a 5MB key.\n3. **Repeated calls actually happen** — verify, don\'t assume.\n4. The function is **expensive enough** that hash + lookup is cheaper than recompute. Memoizing a 50ns function with a 80ns hash is a loss.\n\nThe canonical win: `fib(40)` is ~10⁹ calls without memoization, 40 with it. Exponential → linear because the function has overlapping subproblems.\n\nThe bugs:\n\n- **Memoizing a function with mutable arguments.** `fn(arr)` cached, then caller mutates `arr`. Next call has the same array reference but different contents — wrong cached result. Fix: freeze, copy, or derive a stable key.\n- **Memoizing functions that read time, randomness, environment.** Not pure. Cache returns stale forever.\n- **Unbounded cache in a long-running process.** Slow memory leak. Always pick an eviction policy (LRU, TTL).\n- **Forgetting `this` matters in OO.** A method bound to a different instance is a different function; the cache key needs the receiver.\n- **Cross-request caching with user-specific data.** Per-request memoization (DataLoader style) avoids this.\n\nVariants worth knowing:\n- **Unbounded cache**: small input domains only.\n- **LRU**: good default for hot-path memoization.\n- **TTL**: when stale is acceptable.\n- **Per-request**: lives for one request; safest for user-specific work.',
    },
    {
      level: 'mid',
      question: 'What\'s a performance budget, and what makes one actually useful?',
      answer:
        'A performance budget is a number you commit to, in writing, enforced in CI. "p95 latency stays under 200ms." "Bundle size stays under 250KB gzipped." "Cold start under 800ms."\n\nWithout a budget, performance work has no end condition. With one, you have a binary: in budget or out. If out, it\'s a regression to fix; if in, ship.\n\nWhat to budget:\n- **API endpoints**: p50/p95/p99 latency, error rate.\n- **Frontend**: LCP, INP, CLS, JS bundle size. Lighthouse CI metrics.\n- **Backend jobs**: end-to-end runtime, throughput.\n- **Cold start**: time to first byte for serverless.\n\nWhat *not* to budget:\n- "CPU < 60%" — saturation signal, not a user-facing goal.\n- "Memory < 500MB" — same.\n- "Number of DB queries per request" — useful in dev, not as prod SLI.\n\nThe budget should be observable from outside the service.\n\nMaking it actually work:\n- **Enforced in CI**, not on a wiki. The build fails on regression. The dashboard you have to look at gets ignored; the build that won\'t merge gets attention.\n- **Sub-budgets for diagnosis**: total `< 250ms`, of which DB `< 100ms`, serialization `< 20ms`. Now a regression has a *location*.\n- **Re-negotiable on intentional changes**: a new feature with explicit sign-off may raise the budget. Not silently — explicitly.\n\nIt\'s a ceiling, not a target. Being comfortably under it is the win; being right at it is one bad day from breach.',
    },
    {
      level: 'mid',
      question: 'When does batching help, and what does it cost?',
      answer:
        'Batching combines N small operations into one larger one. The win is amortizing **fixed cost per call**: round-trip latency, lock acquire, syscall overhead, transaction startup. Pay it once instead of N times.\n\n```js\n// Bad: N round trips\nfor (const id of ids) {\n  await db.query(\'SELECT * FROM users WHERE id = ?\', id);\n}\n// Good: 1 round trip\nawait db.query(\'SELECT * FROM users WHERE id IN (?)\', [ids]);\n```\n\nUse when:\n- Per-op fixed cost dominates. A 0.5ms network RTT around 0.01ms of DB work = 50× overhead per call.\n- Downstream supports a batched API.\n- You can tolerate small added latency for per-op (collecting takes time).\n\nFour tactics:\n- **Per-request (DataLoader-style)**: collect within one event-loop tick, fire one batched call. Zero perceived latency; massive RTT win.\n- **Time-window**: buffer for N ms, then flush. Trades small latency for higher throughput.\n- **Size-window**: buffer until N items, then flush. Used when count dominates fixed costs.\n- **Hybrid (size OR time)**: flush at 100 items OR 50ms, whichever first.\n\nCosts and pitfalls:\n\n- **Coordinated omission**: a slow batch holds back N requests\' apparent latency. The p99 you report hides this because each request\'s "latency" includes the batch wait. See the coordinated-omission page.\n- **Failure radius growth**: one bad row fails the whole batch. Pick an API that returns per-row errors, or partition on retry.\n- **Backpressure mismatch**: producer outpaces consumer; the batch fills faster than it drains.\n- **Latency tax for low volume**: time-window batching makes the first request of the day wait 50ms for company that never comes.',
    },
    // --- senior ---
    {
      level: 'senior',
      question: 'Why is tail latency more important than mean, and what specifically causes it?',
      answer:
        'Three reasons:\n\n1. **Users feel the slowest.** A user who got the median doesn\'t think about it; a user who hit p99 remembers the painful one. Tail experiences shape product perception.\n2. **Fan-out amplification.** A request that calls 10 backends and waits for all sees the slowest. Even if each backend\'s p99 is 800ms, P(at least one slow) = 1 − (0.99)^10 ≈ 10% — the user-facing p99 sits near each backend\'s p99.9, much worse than the per-backend p99.\n3. **Retries make it worse.** A timed-out request retries; the retry adds latency. Naive setups turn slow requests into doubly-slow ones.\n\nReal causes of tail spikes:\n\n- **GC pauses** — 50-200ms stop-the-world. Anything running at that moment is in the tail.\n- **Lock contention** — most requests don\'t fight; one in a hundred does.\n- **CPU scheduling** — descheduled by the kernel, especially under cgroup CPU limits.\n- **Network glitches / retransmits** — 200ms penalty per occurrence.\n- **Cold caches** — first request to a new partition hits disk.\n- **Coordinated omission** in measurement — the load tester stops sending requests during stalls, so the stall is recorded as one slow request, not the 10,000 that should have arrived.\n\nMeasure with HDR histograms or t-digests. **You can\'t average percentiles** — two services at p99=200ms don\'t produce a combined p99 of 200ms. Store distributions and compute percentiles globally. Prometheus *summaries* are not mergeable; use histograms.\n\nReducing tail latency means reducing variance: shorter GC pauses, shorter lock hold times, smaller per-request work, **hedging** (fire two parallel requests, take whichever returns first), and **capping work** (return partial results if a deadline is reached).',
    },
    {
      level: 'senior',
      question: 'What is coordinated omission and why does it make most load tests lie?',
      answer:
        'Named by Gil Tene. The most insidious latency-measurement bug.\n\nThe setup — closed-loop load tester:\n\n```python\nwhile running:\n    t0 = time.time()\n    response = send_request()   # blocks during slow phase\n    record_latency(time.time() - t0)\n    sleep(0.001)                # 1000 req/s target\n```\n\nNow suppose the server stalls for 10 seconds. `send_request()` blocks for 10s. The test recorded **one** request with 10-second latency. But during those 10 seconds at 1000 req/s, **10,000 requests** were supposed to arrive — they never did, because the client was waiting.\n\nThe percentile lies:\n- p50 = 5ms (looks fine).\n- p99 = 50ms (looks fine).\n- One outlier of 10s.\n- Mean barely perturbed.\n\nReal users (open-loop arrivals) experience: 10,000 requests waiting, each enduring some fraction of the 10-second delay. Real-world p99 is ~10s. The closed-loop test under-reported by two orders of magnitude.\n\nWhy "coordinated": the client and server are *coordinated* by the blocking call — the client is prevented from issuing more requests during the slowdown.\n\nTwo fixes:\n\n1. **Open-loop generation**: requests fire on a schedule regardless of completion (wrk2, k6 `constant-arrival-rate`, Vegeta).\n2. **HdrHistogram with expected interval**: even with closed-loop, the recorder interpolates the missed samples.\n\nDiagnostic: ask "what would my latency dashboard show if my service stalled for 30s?" If "one request at 30s" — CO is present. If "10,000 requests with latencies between 1ms and 30s" — you\'re fine. Most off-the-shelf tools (ab, wrk, naive scripts) have the bug.',
    },
    {
      level: 'senior',
      question: 'Explain Little\'s Law and how you actually use it.',
      answer:
        '`L = λ × W`. The fundamental conservation law of queueing.\n\n- **L** — average items in the system at steady state.\n- **λ** — throughput (arrivals per unit time).\n- **W** — average latency (time in the system).\n\nIt holds for *any* queueing discipline, *any* distribution. No assumptions about Poisson arrivals, FIFO, etc. As long as the system is stable, Little\'s Law is true.\n\nPractical uses:\n\n1. **Capacity derivation.** "We do 5000 req/s at 200ms average latency. L = 1000 — we have 1000 concurrent in-flight requests on average. Our connection pool, worker pool, thread count all need to handle 1000 concurrent."\n2. **Latency drops concurrency.** Halve latency at the same arrival rate → halve in-flight requests → fewer threads, less memory, lighter pressure.\n3. **Concurrency caps reduce latency.** Bound the number of in-flight requests; for the same throughput, each finishes faster.\n\nPair it with the utilization-latency curve: as ρ → 1, mean wait time `∝ 1/(1−ρ)` — at 0.5 the wait factor is 2, at 0.99 it\'s 100. **Past 70% utilization, latency grows hyperbolic.** This is why you don\'t run at 95% capacity — small bursts catapult you onto the hyperbolic part.\n\nCombined: peak λ + target W tells you L; L plus single-server capacity tells you how many parallel servers; the utilization curve tells you to provision with 30%+ headroom.\n\nThis is the math that turns "we need to scale" into a number — and the one most teams skip in favor of "let\'s just make it bigger."',
    },
    {
      level: 'senior',
      question: 'How does the JVM JIT affect latency, and what should you do about cold-start tail?',
      answer:
        'A JIT-compiled runtime — JVM HotSpot, V8, .NET — interprets code at first, then progressively compiles hot paths. The result: the same code runs **dramatically differently after warmup** than on first invocation. Numbers vary, but roughly:\n\n- First 100 calls: interpreted, often 10-50× slower than warm.\n- Next ~10K: lightly compiled (HotSpot C1 / V8 Sparkplug-Maglev).\n- After enough calls: fully optimized (HotSpot C2 / V8 TurboFan) with inlining, escape analysis, speculative branches.\n\nProduction symptoms:\n- **Spikes after deploys.** Fresh instances handle requests with cold JIT; old ones are warm.\n- **Latency cliffs at low traffic.** A service at 5 req/s/instance may never accumulate enough counter ticks to JIT some methods.\n- **Latency spikes after deoptimization.** A class loaded later invalidated an assumption; back to interpreter until recompile.\n\nStrategies for cold-start tail:\n\n1. **Synthetic warmup at startup**: call hot methods with representative input before joining the load balancer.\n2. **Gradual slow-start**: load balancer ramps traffic to a new instance over 30-120s. Lets JIT catch up under modest load.\n3. **AOT compilation**: GraalVM Native Image, .NET ReadyToRun, V8 snapshots. Trade peak optimization for fast first-request speed. Important for serverless cold starts.\n4. **Tiered compilation tuning**: lower `CompileThreshold` to trigger compilation earlier (with care; can churn compiler).\n5. **Save and replay compilation choices** across restarts (HotSpot Tiered Compilation logs).\n\nFor benchmarking: every JIT-aware framework (JMH, Criterion, Go `testing.B`) does an untimed warmup phase. Skipping it gives you "we measured the interpreter" results.\n\nLanguages without JIT (Go, Rust, C++) avoid this category but have analogous (smaller) effects: code page faults on first call, branch predictor cold, cache cold.',
    },
    {
      level: 'senior',
      question: 'What are the typical sources of lock contention, and how do you diagnose them?',
      answer:
        'Four root causes:\n\n1. **Lock held too long** — code inside the critical section does work that doesn\'t need to be there (I/O, allocation, expensive calls). Fix: compute outside, copy in fast. Critical section should be the smallest possible.\n2. **Lock too coarse** — one lock protects too much. Threads on unrelated sub-state serialize through the same lock. Fix: lock partitioning (sharded locks, per-bucket locks, `ConcurrentHashMap` style segments). Empirically ~4× number of cores is a good starting shard count.\n3. **False sharing** — two threads writing different variables that share a cache line. Cache line bounces between cores via coherence protocol. No lock is held, performance collapses. Fix: padding / alignment to cache-line boundaries.\n4. **Wrong primitive** — a mutex for a read-mostly workload. Fix: RWLock for genuinely read-dominated workloads (only wins if reader sections are non-trivial in length); atomics for counters; lock-free or RCU-style for hot reads.\n\nDiagnosis tooling:\n\n- **JVM**: JFR contention events; async-profiler with `-e lock` produces lock-contention flame graphs.\n- **Go**: `pprof` block profile (`/debug/pprof/block`) shows time waiting on synchronization.\n- **Linux generally**: `perf lock` for kernel-level futex contention events.\n- **Off-CPU flame graphs**: parked threads aren\'t on CPU; off-CPU graphs reveal them.\n\nA cheap scaling diagnostic: run at 1, 2, 4, 8, 16, 32 threads. Plot throughput vs threads.\n- Linear up to N cores → no contention; you\'re CPU-bound.\n- Sublinear early → contention from the start.\n- Linear then flat → contention kicks in at the flatten point.\n- Linear then *down* → destructive interference (often false sharing or CAS-loop livelock).\n\nLock-free isn\'t automatically faster. Under high contention, CAS loops thrash; cache lines bounce. A blocking lock with proper queueing semantics can outperform a hand-rolled lock-free structure. Use lock-free only when contention is genuinely rare.',
    },
    {
      level: 'senior',
      question: 'What is backpressure, and what happens to systems that don\'t have it?',
      answer:
        'Backpressure is the discipline of **letting consumers control producer rate** so the system doesn\'t accumulate unbounded queues. Without it, a fast producer + slow consumer is an OOM waiting to happen, and the bonus is that every queued item is already too stale to be useful by the time it\'s processed.\n\nThe failure mode shape: queue depth grows linearly with the imbalance until the process crashes. Each request sits longer; tail latency tracks queue depth; by the time the consumer gets to an item, the user has given up or retried. Recovery is impossible — you can\'t drain a queue filling faster than you can serve.\n\nFour responses when a bounded queue is full:\n\n1. **Drop new** — reject new requests with 503/EAGAIN. Use when clients can back off.\n2. **Drop old** — evict oldest, accept newest. Use when latest data is most valuable (metrics, real-time feeds).\n3. **Block producer** — producer waits for room. Use for in-process flow control (channels, pipes).\n4. **Slow producer** — distributed systems; producer adapts to a signal.\n\nWhere this shows up: HTTP servers (bounded request queue → 503 over the limit = **load shedding**), message queues (Kafka retention policies), reactive streams (`request(n)`), Node.js streams (`writable.write()` returning false pauses readable), TCP itself (receive window).\n\nKey insight: **failing fast beats failing slow**. A user who waited 5s for a 503 hates you more than one who got the 503 immediately. Shedding under load saves successful requests; without it, all requests degrade.\n\nAdvanced: **adaptive concurrency limits** (Netflix-style, Vegas TCP-inspired) — automatically tune the limit to keep latency at the knee of the throughput-latency curve, no matter how the workload changes.\n\nTwo questions every queue/buffer must answer:\n- What\'s the bound? (Not "unbounded.")\n- What happens when it\'s full? (Pick one of the four.)',
    },
    {
      level: 'senior',
      question: 'How should you tune the garbage collector, in priority order?',
      answer:
        'Counter-intuitive answer: usually you don\'t tune the GC. You tune what *causes* GC work.\n\nThree interventions, in order:\n\n1. **Reduce allocation.** Largest, most reliable lever. Less garbage = fewer GCs = less pause time. Tactics: reuse buffers (`sync.Pool`, `ByteBuffer`), avoid boxing, stream instead of load-into-memory, pre-allocate with known capacity, avoid intermediate collections in filter/map chains.\n2. **Right-size the heap.** Too small = constant GC churn. Too big = longer per-GC and more RAM. Modern collectors target ~30-50% occupancy at steady state; at 80% live data, GC is fighting you. For latency-sensitive services, heap big enough that old-gen utilization stays below ~50%.\n3. **Pick the right collector.** Only after the above:\n   - **JVM**: ZGC, Shenandoah for sub-ms pauses (latency-bound services). G1 default for most. Parallel GC for batch throughput.\n   - **.NET**: Server GC with background mode; sustained-low-latency mode for latency-bound work.\n   - **Go**: default concurrent collector; very few knobs (intentionally).\n\nThe metrics worth watching:\n- **Pause time** (max and p99). Should be single-digit % of total time.\n- **GC frequency**. Every few seconds for young-gen is normal; every 100ms = under-provisioned.\n- **Heap occupancy after GC**. Drops substantially or you have a leak / true working-set growth.\n- **Allocation rate** (bytes/sec). Jump after deploy = new allocation hotpath.\n\nAnti-patterns:\n- `System.gc()` / manual triggering — almost always wrong.\n- Caching forever with no bounds — entries get promoted to old-gen; major GCs amplify.\n- Allocating in a million-element hot loop — even fast GC notices.\n- Tuning flags without measurement (lots of outdated internet advice).\n\nFor latency-critical services, the right move is often **zero-allocation hot paths**: allocate everything up front; reuse buffers; avoid string concatenation; use value types where the language allows. Young-gen GC doesn\'t trigger in steady state. Worth it only after measurement shows GC contributing.',
    },
    // --- staff ---
    {
      level: 'staff',
      question: 'Explain USE and RED methods and when to use each.',
      answer:
        '**USE** (Brendan Gregg, 2012) — for every **resource**, check three signals:\n- **U**tilization: fraction of time the resource was busy.\n- **S**aturation: degree of extra work queued.\n- **E**rrors: count of error events.\n\nA resource is anything with finite capacity: CPUs, memory, disks, network interfaces, file descriptors, thread pools, connection pools. The mechanical use: list every resource; for each, ask the three questions; stop on the first abnormal signal.\n\n**RED** (Tom Wilkie, 2015) — for every **service/endpoint**:\n- **R**ate: requests per second.\n- **E**rrors: errors per second (or fraction).\n- **D**uration: latency distribution.\n\nUSE is about substrate; RED is about product. A service can be USE-clean (no resource saturated) but RED-broken (high p99 from user-space lock contention, not visible as a "resource"). Conversely, USE can red-flag pending trouble (memory exhausting) before RED notices.\n\nGoogle\'s **Four Golden Signals** (Latency, Traffic, Errors, Saturation) is effectively RED + the saturation half of USE. Practical dashboard standard for most services.\n\nWhen to use which:\n- **USE-first** when you suspect resource issues (the service slowed down with no code change).\n- **RED-first** when you suspect application or product issues (a new deploy degraded p99).\n\nDashboards should have both — RED at the top (what users feel), USE underneath (where the bottleneck is). The signal feeding SLIs/SLOs comes from RED. USE feeds capacity alerts.\n\nDeeper than either: distributed tracing for end-to-end latency in microservices, profiling for intra-process performance. USE/RED tells you *where* to point the deeper tooling, not what\'s wrong inside.',
    },
    {
      level: 'staff',
      question: 'How do Little\'s Law, Amdahl\'s Law, and the Universal Scalability Law fit together?',
      answer:
        'Three formulas, each a one-liner, that together bound what a system can do.\n\n**Little\'s Law**: `L = λ × W`. Equality at steady state. Any two determine the third. Gives you concurrency from throughput and latency.\n\n**Amdahl\'s Law**: `Speedup(N) ≤ 1 / ((1 − p) + p/N)`. Upper bound on parallel speedup, where `p` is the parallelizable fraction. The asymptote is `1 / (1 − p)` — at `p = 0.9`, max speedup is 10× no matter how many cores. The serial fraction is the floor.\n\n**Universal Scalability Law** (Gunther): `Speedup(N) = N / (1 + α(N−1) + βN(N−1))`. Adds two terms:\n- α (contention) ≈ Amdahl-style serial fraction.\n- β (coherence) — cost of cross-worker coordination (cache invalidations, lock-line bouncing, mutex hot-spots).\n\nThe β term grows *quadratically* in N. Past a critical N, more workers make things **worse** — throughput peaks and then declines. This is what real benchmarks show (Amdahl never predicts decline; USL does).\n\nHow they connect:\n- **Amdahl bounds peak**: how much speedup parallelism can buy.\n- **USL explains where peak occurs and what happens past it**: there\'s an N_max beyond which adding workers loses.\n- **Little tells you concurrency required for a target (throughput, latency)**: tells you how many parallel workers you need.\n\nA worked flow:\n- Goal: 10,000 req/s at 200ms latency.\n- Little: L = 2000 concurrent in-flight requests.\n- USL: at measured α=0.05, β=0.001, peak is at N≈30 workers per machine.\n- Therefore: `ceil(2000/30) ≈ 67 instances`, 30 workers each.\n\nBiggest practical takeaway: **focus on reducing the serial fraction**. Locks, single-leader writes, sequence-number generators — these are what Amdahl caps you on. Patterns that reduce it: sharding by key, eventually-consistent reads, CRDTs, read replicas. Patterns that increase it: global locks, single-sequence-claim writes, leader election on every write.',
    },
    {
      level: 'staff',
      question: 'How do you set up performance regression detection that doesn\'t flap?',
      answer:
        'Five components:\n\n1. **A reproducible benchmark suite.** End-to-end / endpoint benchmarks (closest to user-felt) are the highest value; component benchmarks for genuinely hot paths; microbenchmarks rarely.\n2. **A deterministic execution environment.** Same hardware, OS, CPU governor, low noise. Cloud VMs are usually too noisy. Dedicated CI runners, pinned frequency, no neighbors.\n3. **Statistical comparison, not threshold.** Confidence intervals between baseline and PR — fail only when the CI of the new measurement clearly exceeds the CI of baseline. Mann-Whitney U or bootstrap-based comparison handles non-normal latency distributions better than t-tests.\n4. **A blocking failure mode.** PR can\'t merge on regression. Dashboards get ignored; build gates get attention.\n5. **A bypass for legitimate regressions** — explicit baseline update with sign-off when the new feature legitimately costs more. Not silent.\n\nThe variance problem: two runs of the same benchmark on the same machine routinely differ by 5-15% with no code change. Solutions in order of effort: run 30+ iterations and use medians; pin frequency / disable scaling / pin to specific cores; use a quiet machine; use statistical tools (Criterion, JMH, bootstrap comparison).\n\nHard-threshold rules (`>5% slower fails`) flap constantly. CI-interval rules don\'t.\n\nWhat to benchmark, in priority order:\n- Endpoint benchmarks for the top 5-10 hot paths (most robust, most informative).\n- Component benchmarks for genuinely hot internal functions.\n- Microbenchmarks only when needed (library code, comparing two algorithms).\n\nBaseline management: PR-blocking against latest main with confidence intervals; weekly/monthly comparison against a "golden baseline" to catch slow drift.\n\nReporting: per-scenario deltas with CIs, comparison to recent runs (trend), direct link to differential flame graph for regressions. The PR comment that just says "8% regression, see logs" makes the engineer dig; one with a flame-graph diff lets them fix in minutes.\n\nAnti-patterns: treating perf CI as advisory (not blocking), shared infrastructure for benchmarks (variance swamps signal), reporting only mean (always pair with distribution), ignoring "too-good" improvements (sometimes a dead-code-eliminated test).',
    },
    {
      level: 'staff',
      question: 'How do you do capacity planning that actually predicts production behavior?',
      answer:
        'Three honest questions, in order:\n\n1. **How much can each unit handle at SLO?** Not max throughput — throughput at which latency stays within budget. For p99 < 300ms, an instance maxing out at 600 req/s might only sustain 400 req/s at SLO. The capacity number is 400.\n2. **What does demand look like?** Steady-state today, growth trajectory, daily/weekly/yearly seasonality, expected event-driven spikes. Peak hour drives provisioning, not average.\n3. **How much headroom?** Typically 2-3× peak for stateless services with fast scaling; 3-4× for slow-scaling (warmup, stateful, sharded) or strict SLOs.\n\nWhy not run at 95% utilization: the latency-utilization curve is hyperbolic past 70%, scaling has latency (instances take 30s-5min to warm), and failure correlation (AZ outage takes 1/3 of capacity).\n\nStateful systems (DB, cache, queues) are harder — capacity changes take days, write rate is single-leader-bound, sharding boundaries are sticky. Plan further ahead.\n\nCommon failure modes:\n- **Provisioning for average** — peak is when the outage happens.\n- **Forgetting compounding** — scale app from 10 to 100 instances; now DB has 10× connection pressure it can\'t handle.\n- **Cliffs** — the 11th node trips kernel socket limit / S3 partition limit / DB max connections. Capacity is non-linear past a limit.\n- **Single-AZ planning** — adequate when nothing fails, insufficient when one AZ degrades.\n- **Cache effectiveness assumptions** — a new feature changes the access pattern; hit rate drops; effective capacity halves.\n- **Auto-scaling lag** — reactive metrics are the past; auto-scaling overshoots and undershoots.\n\nFor queueing-heavy workloads: USL fit (run benchmarks at increasing concurrency; find α and β) predicts N_max — past it, more workers degrade total. Erlang C for call-center-style queueing.\n\nCadence: monthly review of trends, quarterly full refresh and reserved-capacity decisions, annual strategic (multi-region, DC contracts), event-driven before known traffic events. Pair with quarterly chaos exercise (take out an AZ) to validate that the plan actually works under the failure mode you nominally planned for.',
    },
    {
      level: 'staff',
      question: 'What does "tail at scale" mean and how do you fight it?',
      answer:
        'From Dean & Barroso\'s paper. Once you fan out a user request to N backends, **the user\'s p99 is dominated by the slowest backend\'s tail, not by any individual backend\'s mean**.\n\nFor N independent backends each with 1% tail-event probability:\n- `P(user hits ≥1 tail event) = 1 − (0.99)^N`\n- N=1: 1%\n- N=10: 9.6%\n- N=100: 63%\n\nThe user-facing service\'s effective p99 sits near each backend\'s **p99.9** — substantially worse than the individual backend p99. Even rare events become probable at the fan-out level.\n\nMitigations:\n\n1. **Reduce N.** Cache aggressively to remove backend calls; batch requests that target the same backend; precompute joined views.\n2. **Hedged requests / speculative execution.** Send the same request to two backends after a short delay; take whichever returns first. Used by Google for tail-bound systems. Doubles load only on the slow tail percentage. Bigtable, Spanner do this.\n3. **Cancellation on first success.** Once the hedge wins, cancel the others quickly. Need cooperative cancellation (gRPC context cancellation).\n4. **Better load balancing.** Two-choice random ("power of two") — randomly pick two backends, send to the one with shorter queue. Dramatically reduces tail compared to round-robin.\n5. **Tied requests.** Send to multiple backends with a "tied" marker; the first to start cancels the others. Variant of hedging.\n6. **Tail-tolerant caching.** Serve a slightly stale response if the live one isn\'t ready within deadline.\n7. **Per-backend p99 reduction** — push hard on each backend\'s p99. The user p99 falls because the fan-out amplification has less to amplify.\n8. **Cap the work / deadline propagation.** Each layer enforces a remaining time budget; backend returns partial result if deadline approaches.\n\nObservability requirement: measure per-backend tails *separately* and the user-felt tail *together*. The gap between them quantifies amplification. Trace-based percentile breakdowns are the right tool.\n\nWhat\'s structurally different about tail-bound work: small mean improvements don\'t help much; **reducing variance** is the only durable win. GC tuning, lock contention reduction, cgroup CPU limit removal, hedging — these reduce variance per backend, which propagates through the fan-out.',
    },
  ],
};
